/**
 * video.c - Realtime MODEM_DIAG -> PARLIO RX -> 16K ring -> Phase5 TX -> DAC.
 *
 * Implements the complete production datapath for C5VRX-3:
 *
 *   MODEM_DIAG full Q4/I4 @ 40 MS/s
 *     -> PARLIO RX POS edge @ 40 MHz
 *     -> 16 KiB cyclic raw DMA ring (HP SRAM)
 *     -> PARLIO TX @ 40 MHz + Phase5 TX BitScrambler (fm.bsasm)
 *     -> [D,D] 6-bit CVBS @ 20 MS/s unique / 40 MHz DAC clock
 *     -> 6-bit resistor DAC
 *
 * Reference: Seamless Golden 16K (build-golden-notel) -- proven best live build.
 *
 * Fixed production constants (NOT configurable at runtime):
 *   IQ rate:        40 MHz
 *   DAC rate:       40 MHz physical ([D,D] = 20 MS/s unique CVBS)
 *   Ring:           16384 bytes (HP SRAM, DMA-aligned)
 *   Pedestal:       20   (hardcoded in FM LUT)
 *   Gain:           2    (hardcoded in FM LUT)
 *   Polarity:       current-minus-previous (hardcoded in FM LUT)
 *   RX sample edge: POS
 *   TX shift edge:  NEG
 *   BS EOF:         downstream (PARLIO TX loop never generates downstream EOF)
 *   BS tail:        0 bytes
 *
 * After video_start() the CPU has nothing to do. No periodic tasks or timers.
 */

#include "video.h"
#include "rf.h"
#include "osd_font.h"

#include <stdint.h>
#include <string.h>

#include "driver/bitscrambler.h"
#include "driver/gpio.h"
#include "driver/parlio_bitscrambler.h"
#include "driver/parlio_rx.h"
#include "driver/parlio_tx.h"
#include "esp_attr.h"
#include "esp_cache.h"
#include "esp_log.h"
#include "esp_rom_sys.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "soc/parl_io_struct.h"
#include "soc/bitscrambler_struct.h"
#include "soc/ahb_dma_struct.h"
#include "soc/pcr_struct.h"
#include "modem/modem_syscon_reg.h"
#include "hal/dma_types.h"
#include "esp_clock_output.h"

/* Hardware diagnostic counters in IRAM to measure transport hiccups without printf spam */
typedef struct {
    uint32_t parl_rx_wovf_count;
    uint32_t parl_tx_rempty_count;
    uint32_t parl_tx_eof_count;
    uint32_t bs_fifo_empty_count;
    uint32_t bs_eof_overload_count;
    uint32_t checks;
} hw_transport_counters_t;

static volatile hw_transport_counters_t s_hw_counters;

/* fm.bsasm program symbol generated by target_bitscrambler_add_src(). */
BITSCRAMBLER_PROGRAM(s_fm_program, "fm");

/* ----- Fixed production constants ----- */
#define IQ_RATE_HZ       40000000u   /* MODEM_DIAG / PARLIO RX clock */
#define DAC_RATE_HZ      40000000u   /* PARLIO TX clock ([D,D] = 20 MS/s unique) */
#define RAW_RING_BYTES   16384u      /* 16384 byte cyclic ring (16 KiB Seamless Golden) */
#define DAC_IDLE_CODE    20u         /* Pedestal 20 (sync tip level) */
#define BOOT_BTN_GPIO    GPIO_NUM_28 /* Seeed Studio XIAO ESP32-C5 BOOT Button */
#define OSD_BOOT_BTN_ENABLE_DEFAULT  0 /* 0 = Disabled by default (Safe Flight Mode) */

/* NTSC 240p Composite Video Synthesized OSD Engine (60.012 Hz, 1272 words/line) */
#define NTSC_LINE_WORDS   1272u
#define NTSC_LINE_BYTES   (NTSC_LINE_WORDS * 2u) /* 2544 bytes @ 40 MS/s DAC clock */
#define NTSC_TOTAL_LINES  262u
#define OSD_MENU_ROWS     7u
#define OSD_FONT_HEIGHT   8u
#define OSD_ACTIVE_LINES  (OSD_MENU_ROWS * OSD_FONT_HEIGHT) /* 56 scanlines */

/* Synthesized IQ cycles for the embedded Phase5 LUT.
 *
 * Phase5 has 32 uniform polar phase bins (0..31) and a 50 ns discriminator.
 * For any 4-sample repeating pattern, the sum of phase deltas mod 32 must be 0
 * to guarantee zero phase drift across pixels, scanlines, and DMA frames:
 *
 *   BLACK: Phase delta 0  (P0 -> P0 -> P0 -> P0 -> P0)
 *          Byte 0x50 repeated: exact DAC [20, 20, 20, 20] (0.33V Pedestal/Blanking)
 *   SYNC:  Phase delta -8 (P0 -> P24 -> P16 -> P8 -> P0)
 *          Bytes {0x08, 0x80, 0x05, 0x50}: exact DAC [0, 0, 0, 0] (0.0V Sync Tip)
 *   WHITE: Phase delta +8 (P0 -> P8 -> P16 -> P24 -> P0)
 *          Bytes {0x05, 0x80, 0x08, 0x50}: exact DAC [63, 63, 63, 63] (1.0V Peak White)
 *
 * Every segment and font pixel is an exact multiple of 4 words, guaranteeing
 * that all transitions close on Phase 0 without transient glitch spikes.
 */
static const uint8_t s_black_iq[4] = {0x50u, 0x50u, 0x50u, 0x50u};
static const uint8_t s_sync_iq[4]  = {0x08u, 0x80u, 0x05u, 0x50u};
static const uint8_t s_white_iq[4] = {0x05u, 0x80u, 0x08u, 0x50u};

static inline uint16_t iq_word(uint8_t b)
{
    return (uint16_t)(((uint16_t)b << 8) | b);
}

static inline uint16_t get_black_word(int idx)
{
    return iq_word(s_black_iq[idx & 3]);
}

static inline uint16_t get_sync_word(int idx)
{
    return iq_word(s_sync_iq[idx & 3]);
}

static inline uint16_t get_white_word(int idx)
{
    return iq_word(s_white_iq[idx & 3]);
}

/* Cache synchronization helpers for DMA buffers and descriptors on ESP32-C5.
 * Aligns address down and size up to 64-byte cache line boundaries so esp_cache_msync
 * never fails with ESP_ERR_INVALID_ARG on unaligned descriptors or buffers. */
static inline void sync_dma_c2m(const void *addr, size_t size)
{
    if (!addr || size == 0) return;
    uint32_t start = (uint32_t)addr & ~(64u - 1u);
    uint32_t end = ((uint32_t)addr + size + 63u) & ~(64u - 1u);
    (void)esp_cache_msync((void *)start, end - start,
                          ESP_CACHE_MSYNC_FLAG_DIR_C2M | ESP_CACHE_MSYNC_FLAG_UNALIGNED);
}

static inline void sync_dma_m2c(const void *addr, size_t size)
{
    if (!addr || size == 0) return;
    uint32_t start = (uint32_t)addr & ~(64u - 1u);
    uint32_t end = ((uint32_t)addr + size + 63u) & ~(64u - 1u);
    (void)esp_cache_msync((void *)start, end - start,
                          ESP_CACHE_MSYNC_FLAG_DIR_M2C | ESP_CACHE_MSYNC_FLAG_UNALIGNED);
}

/* Static NTSC CVBS scanline buffers & 262-node DMA descriptor chain in HP SRAM */
static DMA_ATTR __attribute__((aligned(64))) uint8_t s_blank_line[NTSC_LINE_BYTES];
static DMA_ATTR __attribute__((aligned(64))) uint8_t s_vsync_line[NTSC_LINE_BYTES];
static DMA_ATTR __attribute__((aligned(64))) uint8_t s_eq_line[NTSC_LINE_BYTES];
static DMA_ATTR __attribute__((aligned(64))) uint8_t s_osd_lines[OSD_ACTIVE_LINES][NTSC_LINE_BYTES];
static DMA_ATTR __attribute__((aligned(64))) dma_descriptor_t s_osd_dma_nodes[NTSC_TOTAL_LINES];

/* OSD State */
static volatile bool s_menu_active = false;
static volatile bool s_osd_boot_btn_enabled = (OSD_BOOT_BTN_ENABLE_DEFAULT != 0);
static volatile int s_menu_cursor = 0;
static int s_menu_timeout_ticks = 0;

/* TX GPIO mapping: 6-bit resistor DAC.
 * Order: DAC bit 0 (LSB) .. DAC bit 5 (MSB) on data_gpio_nums[0..5].
 * Bits 6..7 unused (set to -1).
 * Verified against C5VRX-2 realtime.c (standard 8-bit PARLIO TX, non-parlio4). */
static const int s_dac_gpio[8] = {23, 24, 11, 12, 8, 9, -1, -1};

_Static_assert(IQ_RATE_HZ == 40000000u, "IQ rate must be 40 MHz");
_Static_assert(DAC_RATE_HZ == 40000000u, "DAC rate must be 40 MHz");
_Static_assert(RAW_RING_BYTES == 16384u, "Ring must be exactly 16384 bytes");

static const char *TAG = "c5vrx3_video";

/* DMA-aligned ring buffer in HP SRAM.
 * RX GDMA writes at 40 MB/s; TX GDMA reads at 40 MB/s.
 * TX starts one block (4096 bytes = 102.4 µs) behind RX; they share
 * PLL_F240M/6, so separation cannot drift during normal operation. */
static DMA_ATTR __attribute__((aligned(64))) uint8_t s_raw_ring[RAW_RING_BYTES];

static parlio_rx_unit_handle_t      s_rx;
static parlio_rx_delimiter_handle_t s_rx_delimiter;
static parlio_tx_unit_handle_t      s_tx;

/* ----- PARLIO RX setup ----- */

static esp_err_t prepare_rx(void)
{
    /* Proven PARLIO RX config with clean internal SPLL clock */
    const parlio_rx_unit_config_t cfg = {
        .trans_queue_depth = 1u,
        .max_recv_size     = sizeof(s_raw_ring),
        .dma_burst_size    = 32u,
        .data_width        = 8u,
        .clk_src           = PARLIO_CLK_SRC_DEFAULT,
        .ext_clk_freq_hz   = 0u,
        .exp_clk_freq_hz   = IQ_RATE_HZ,
        .clk_in_gpio_num   = -1,
        .clk_out_gpio_num  = -1,
        .valid_gpio_num    = -1,
        /* GPIO order must match s_iq_pins[] in rf.c:
         * Q[9:6] on GPIO 1,0,25,7 then I[9:6] on GPIO 10,5,3,4. */
        .data_gpio_nums    = {
            GPIO_NUM_1, GPIO_NUM_0, GPIO_NUM_25, GPIO_NUM_7,
            GPIO_NUM_10, GPIO_NUM_5, GPIO_NUM_3, GPIO_NUM_4,
        },
        .flags = {
            .free_clk    = true,   /* RX clock is derived from PHY, not gated */
            .clk_gate_en = false,
            .allow_pd    = false,
        },
    };
    esp_err_t err = parlio_new_rx_unit(&cfg, &s_rx);
    if (err != ESP_OK) return err;

    /* Soft delimiter in infinite (partial_rx_en) mode.
     * POS sample edge -- proven correct for internal clock. */
    const parlio_rx_soft_delimiter_config_t delim_cfg = {
        .sample_edge  = PARLIO_SAMPLE_EDGE_POS,
        .bit_pack_order = PARLIO_BIT_PACK_ORDER_LSB,
        .eof_data_len = sizeof(s_raw_ring),
        .timeout_ticks = 0u,
    };
    err = parlio_new_rx_soft_delimiter(&delim_cfg, &s_rx_delimiter);
    if (err != ESP_OK) return err;

    return parlio_rx_unit_enable(s_rx, false);
}

/* ----- PARLIO TX setup ----- */

static esp_err_t prepare_tx(void)
{
    /* Proven PARLIO TX config from Seamless Golden 16K reference.
     * 8-bit data width, 40 MHz output, NEG shift edge, LSB packing.
     * BitScrambler decorated on the TX unit (not RX -- C5 has one BS). */
    const parlio_tx_unit_config_t cfg = {
        .clk_src              = PARLIO_CLK_SRC_DEFAULT,
        .clk_in_gpio_num      = -1,
        .input_clk_src_freq_hz = 0u,
        .output_clk_freq_hz   = DAC_RATE_HZ,
        .data_width           = 8u,
        .data_gpio_nums       = {
            s_dac_gpio[0], s_dac_gpio[1], s_dac_gpio[2], s_dac_gpio[3],
            s_dac_gpio[4], s_dac_gpio[5], s_dac_gpio[6], s_dac_gpio[7],
        },
        .clk_out_gpio_num  = -1,
        .valid_gpio_num    = -1,
        .valid_start_delay = 0,
        .valid_stop_delay  = 0,
        .trans_queue_depth = 1u,
        .max_transfer_size = sizeof(s_raw_ring),
        .dma_burst_size    = 32u,
        .shift_edge        = PARLIO_SHIFT_EDGE_NEG,   /* FIXED: NEG (RX is POS) */
        .bit_pack_order    = PARLIO_BIT_PACK_ORDER_LSB,
    };
    esp_err_t err = parlio_new_tx_unit(&cfg, &s_tx);
    if (err != ESP_OK) return err;

    /* Decorate TX with BitScrambler (TX-only; C5 has one shared BS core). */
    err = parlio_tx_unit_decorate_bitscrambler(s_tx);
    if (err != ESP_OK) return err;

    return parlio_tx_unit_enable(s_tx);
}

/* ----- Start RX cyclic ring ----- */

static esp_err_t start_rx(void)
{
    esp_err_t err = parlio_rx_soft_delimiter_start_stop(s_rx, s_rx_delimiter, true);
    if (err != ESP_OK) return err;
    const parlio_receive_config_t cfg = {
        .delimiter = s_rx_delimiter,
        .flags = {
            .partial_rx_en   = true,
            .indirect_mount  = false,
        },
    };
    return parlio_rx_unit_receive(s_rx, s_raw_ring, sizeof(s_raw_ring), &cfg);
}

/* ----- Start TX loop ----- */

static esp_err_t start_tx(void)
{
    /* Phase5 LUT is embedded in fm.bsasm -- no runtime bitscrambler_load_lut().
     * Hardware oracle v9 proved embedded LUT is byte-exact at 20 MS/s;
     * a separately preloaded LUT is NOT retained by the active PARLIO TX run. */
    const parlio_transmit_config_t cfg = {
        .idle_value          = DAC_IDLE_CODE,
        .bitscrambler_program = s_fm_program,
        .flags.loop_transmission = true,  /* Infinite -- never generates downstream EOF */
    };
    /* TX reads sizeof(s_raw_ring) * 8 bits, then loops.
     * loop_transmission=true means PARLIO TX never stops; the BitScrambler
     * with eof_on=downstream therefore runs uninterrupted forever. */
    return parlio_tx_unit_transmit(s_tx, s_raw_ring,
                                   sizeof(s_raw_ring) * 8u, &cfg);
}

static int s_rx_dma_ch = -1;
static int s_tx_dma_ch = -1;

static inline uint32_t get_rx_dma_offset(uint32_t *out_dscr_addr)
{
    if (s_rx_dma_ch < 0 || s_rx_dma_ch >= 3) return 0;
    uint32_t dscr_addr = AHB_DMA.channel[s_rx_dma_ch].in.in_dscr_bf0.val;
    if (out_dscr_addr) *out_dscr_addr = dscr_addr;
    if (dscr_addr >= 0x40800000u && dscr_addr < 0x40860000u) {
        dma_descriptor_t *dscr = (dma_descriptor_t *)(uintptr_t)dscr_addr;
        uint8_t *buf = (uint8_t *)dscr->buffer;
        if (buf >= s_raw_ring && buf < s_raw_ring + sizeof(s_raw_ring)) {
            return (uint32_t)(buf - s_raw_ring);
        }
    }
    return 0;
}

static inline uint32_t get_tx_dma_offset(uint32_t *out_dscr_addr)
{
    if (s_tx_dma_ch < 0 || s_tx_dma_ch >= 3) return 0;
    uint32_t dscr_addr = AHB_DMA.channel[s_tx_dma_ch].out.out_dscr_bf0.val;
    if (out_dscr_addr) *out_dscr_addr = dscr_addr;
    if (dscr_addr >= 0x40800000u && dscr_addr < 0x40860000u) {
        dma_descriptor_t *dscr = (dma_descriptor_t *)(uintptr_t)dscr_addr;
        uint8_t *buf = (uint8_t *)dscr->buffer;
        if (buf >= s_raw_ring && buf < s_raw_ring + sizeof(s_raw_ring)) {
            return (uint32_t)(buf - s_raw_ring);
        }
    }
    return 0;
}

#define MAX_RING_DESCRIPTORS 16

typedef struct {
    dma_descriptor_t *dscr;
    uint8_t *buffer;
    uint32_t length;
} osd_dscr_node_t;

static osd_dscr_node_t s_rx_dscr_nodes[MAX_RING_DESCRIPTORS];
static int s_rx_dscr_count = 0;

static osd_dscr_node_t s_tx_dscr_nodes[MAX_RING_DESCRIPTORS];
static int s_tx_dscr_count = 0;

static inline int find_dscr_index(const osd_dscr_node_t *nodes, int count, uint32_t addr)
{
    for (int i = 0; i < count; i++) {
        if ((uintptr_t)nodes[i].dscr == addr) return i;
    }
    return -1;
}

static int patch_descriptors_clear_eof(int dma_ch, bool is_rx)
{
    if (dma_ch < 0 || dma_ch >= 3) return 0;
    uint32_t first_addr = is_rx ? AHB_DMA.channel[dma_ch].in.in_dscr_bf0.val
                                : AHB_DMA.channel[dma_ch].out.out_dscr_bf0.val;
    if (first_addr < 0x40800000u || first_addr >= 0x40860000u) return 0;

    dma_descriptor_t *curr = (dma_descriptor_t *)(uintptr_t)first_addr;
    int count = 0;
    if (is_rx) s_rx_dscr_count = 0;
    else s_tx_dscr_count = 0;

    while (curr && count < MAX_RING_DESCRIPTORS) {
        curr->dw0.suc_eof = 0;
        sync_dma_c2m(curr, sizeof(dma_descriptor_t));

        if (is_rx) {
            s_rx_dscr_nodes[count].dscr = curr;
            s_rx_dscr_nodes[count].buffer = (uint8_t *)curr->buffer;
            s_rx_dscr_nodes[count].length = curr->dw0.size ? curr->dw0.size : 4092u;
        } else {
            s_tx_dscr_nodes[count].dscr = curr;
            s_tx_dscr_nodes[count].buffer = (uint8_t *)curr->buffer;
            s_tx_dscr_nodes[count].length = curr->dw0.size ? curr->dw0.size : 4092u;
        }

        curr = curr->next;
        count++;
        if ((uintptr_t)curr == first_addr) break;
    }
    if (is_rx) s_rx_dscr_count = count;
    else s_tx_dscr_count = count;

    __asm__ __volatile__("fence rw, rw" ::: "memory");
    return count;
}

/* Pick a descriptor that RX has already completed, rather than sampling a
 * fixed address that GDMA may be overwriting at the same instant. This keeps
 * AGC/coherence decisions based on one coherent 256-byte RF snapshot. */
static uint8_t *get_completed_rx_sample_window(size_t bytes)
{
    if (s_rx_dma_ch < 0 || s_rx_dma_ch >= 3 || s_rx_dscr_count < 2) {
        return s_raw_ring;
    }

    uint32_t current_addr = AHB_DMA.channel[s_rx_dma_ch].in.in_dscr_bf0.val;
    int current_idx = find_dscr_index(s_rx_dscr_nodes, s_rx_dscr_count, current_addr);
    if (current_idx < 0) {
        return s_raw_ring;
    }

    for (int back = 1; back < s_rx_dscr_count; ++back) {
        int idx = (current_idx - back + s_rx_dscr_count) % s_rx_dscr_count;
        uint8_t *buf = s_rx_dscr_nodes[idx].buffer;
        uint32_t len = s_rx_dscr_nodes[idx].length;
        if (buf && len >= bytes &&
            buf >= s_raw_ring && (buf + bytes) <= (s_raw_ring + sizeof(s_raw_ring))) {
            return buf;
        }
    }
    return s_raw_ring;
}

/* =========================================================================
 * Receiver Modes, Dual-Loop AGC, Bandwidth Gearbox, and AFC State
 *
 * Direct Q4/I4 vector power: P[n] = I[n]^2 + Q[n]^2
 * Target: P_median in [20, 30] (effective radius ~4.5 - 5.5, phase sigma ~3.3 deg)
 *
 * Fast Overload Rem: Instant drop (-4 or -6) when n_clip >= 4 AND P_median > 18.
 * FM Phase Coherence: Q_phase = count(P >= 8 && dot > 0 && |cross| <= dot) * 100 / 255.
 *
 * 3-State Machine:
 *   - SEARCH: No carrier / lost carrier (q_phase < 40%, P_med < 14). Default G=32.
 *   - LEARN:  Probing & centering toward P_median in [20, 30].
 *   - TRACK:  Carrier locked! Hysteresis deadband [18, 32]. ZERO register writes.
 *
 * Modes:
 *   - ANALOG_AGC_SHADOW: Realtime state machine & Q_phase active, physical gain frozen.
 *   - ANALOG_AGC_ACTIVE: Default! Actively updates physical RF gain registers.
 *   - ANALOG_AGC_MANUAL: Fixed gain controlled by user (+ / - keys).
 * ========================================================================= */

typedef enum {
    ANALOG_AGC_SHADOW = 0,
    ANALOG_AGC_ACTIVE = 1,
    ANALOG_AGC_MANUAL = 2,
} analog_agc_mode_t;

typedef enum {
    AGC_STATE_SEARCH = 0,
    AGC_STATE_LEARN  = 1,
    AGC_STATE_TRACK  = 2,
} agc_state_t;

typedef enum {
    BW_GEAR_AUTO = 0, /* Dynamic Bandwidth Adaptation: BW40 normally, BW20 in deep fade */
    BW_GEAR_BW40 = 1, /* Forced BW40 (20 MHz baseband, full color) */
    BW_GEAR_BW20 = 2, /* Forced BW20 (10 MHz baseband, +3 dB sensitivity) */
} bw_gear_mode_t;

typedef enum {
    AFC_MODE_AUTO = 0, /* Auto Carrier Centering: centers within safe +/-1.5 MHz bound when locked */
    AFC_MODE_HOLD = 1, /* AFC Hold: freeze current offset */
    AFC_MODE_OFF  = 2, /* AFC Off: reset to 0 kHz offset */
} afc_mode_t;

static volatile analog_agc_mode_t s_agc_mode = ANALOG_AGC_ACTIVE;
static volatile agc_state_t s_agc_state = AGC_STATE_SEARCH;
static volatile bw_gear_mode_t s_bw_gear_mode = BW_GEAR_AUTO;
/* WBFM instantaneous phase slope contains the video modulation itself.
 * The short-window CFO estimator is useful diagnostics, but it is not yet a
 * calibrated LO-error estimator. Never retune automatically at boot. */
static volatile afc_mode_t s_afc_mode = AFC_MODE_OFF;
static volatile bool s_current_bw40 = true;
static volatile uint8_t s_current_gain = 52u;   /* Physical RF gain applied */
static volatile uint8_t s_shadow_gain = 52u;    /* Controller recommended gain */
static volatile int s_last_p_median = 25;
static volatile int s_last_q_phase = 0;
static volatile int s_last_n_clip = 0;
static volatile int s_last_n_origin = 0;
static volatile int s_cfo_khz = 0;              /* Carrier Frequency Offset in kHz */

/* =========================================================================
 * Synthesized IQ Local NTSC 240p OSD Menu Engine & Controller
 *
 * Architecture:
 * 1. FLIGHT MODE (Live Video):
 *    Zero CPU interference. The RX GDMA -> raw ring -> Phase5 BS -> TX GDMA
 *    hardware pipeline runs 100% untouched.
 * 2. OSD MENU MODE (Hold BOOT >= 600 ms):
 *    PARLIO TX GDMA switches to a pre-built 262-node circular DMA descriptor
 *    chain streaming clean synthesized IQ samples into the Phase5 BitScrambler.
 *    The BitScrambler demodulates these into textbook NTSC 240p composite video:
 *    - H-Sync tip:  Exact DAC code 0  (0.0V sync tip)
 *    - Blanking:    Exact DAC code 20 (0.33V pedestal)
 *    - White text:  Exact DAC code 63 (1.0V peak white)
 *    - 60.012 Hz field rate with phase-coherent scanline boundaries.
 * 3. EXIT (Hold BOOT on SAVE & EXIT or 12s inactivity timeout):
 *    Instantly re-establishes 8192-byte RX/TX separation and restores live video.
 * ========================================================================= */

static void osd_draw_string(int row_idx, int col_words, const char *str)
{
    if (row_idx < 0 || row_idx >= (int)OSD_MENU_ROWS) return;
    int base_line = row_idx * (int)OSD_FONT_HEIGHT;
    int start_col = 192 + col_words;

    int char_idx = 0;
    while (*str && (start_col + char_idx * 32 + 32) < 1240) {
        char ch = *str++;
        int font_idx = (ch >= 32 && ch <= 126) ? (ch - 32) : 0;

        for (int r = 0; r < 8; r++) {
            uint8_t bits = s_font8x8[font_idx][r];
            uint16_t *line_ptr = (uint16_t *)s_osd_lines[base_line + r];
            int p = start_col + char_idx * 32;

            for (int b = 7; b >= 0; b--) {
                if (bits & (1 << b)) {
                    /* White pixel: 4 words of white cycle -> exact 4-sample integer cycle ending at Phase 0 */
                    line_ptr[p]     = get_white_word(0);
                    line_ptr[p + 1] = get_white_word(1);
                    line_ptr[p + 2] = get_white_word(2);
                    line_ptr[p + 3] = get_white_word(3);
                } else {
                    /* Black pixel: exact DAC 20 cycle, closing on P0 */
                    line_ptr[p]     = get_black_word(0);
                    line_ptr[p + 1] = get_black_word(1);
                    line_ptr[p + 2] = get_black_word(2);
                    line_ptr[p + 3] = get_black_word(3);
                }
                p += 4;
            }
        }
        char_idx++;
    }

    /* Pad remaining columns in this row up to 34 chars with black pixels */
    while (char_idx < 34 && (start_col + char_idx * 32 + 32) < 1240) {
        for (int r = 0; r < 8; r++) {
            uint16_t *line_ptr = (uint16_t *)s_osd_lines[base_line + r];
            int p = start_col + char_idx * 32;
            for (int b = 0; b < 32; b++) {
                line_ptr[p + b] = get_black_word(b);
            }
        }
        char_idx++;
    }
}

static void osd_render_menu(void);

static void osd_init_buffers(void)
{
    /* Pre- and post-equalizing pulse line:
     * EIA RS-170 standard: 2 half-line equalizing pulses per line.
     * Each half-line (636 words = 31.8 µs):
     * - 48 words (2.4 µs) of sync tip (DAC code 0)
     * - 588 words (29.4 µs) of pedestal / blanking (DAC code 20)
     * 48 + 588 + 48 + 588 = 1272 words (63.6 µs = 2544 bytes).
     * All segments are multiples of 4 -> exact Phase 0 closure! */
    uint16_t *eq_words = (uint16_t *)s_eq_line;
    int eq_pos = 0;
    for (int i = 0; i < 48; i++)  eq_words[eq_pos++] = get_sync_word(i);
    for (int i = 0; i < 588; i++) eq_words[eq_pos++] = get_black_word(i);
    for (int i = 0; i < 48; i++)  eq_words[eq_pos++] = get_sync_word(i);
    for (int i = 0; i < 588; i++) eq_words[eq_pos++] = get_black_word(i);

    /* V-Sync broad pulse serration line:
     * EIA RS-170 standard: 2 half-line broad pulses per line.
     * Each half-line (636 words = 31.8 µs):
     * - 540 words (27.0 µs) of sync tip (DAC code 0)
     * - 96 words (4.8 µs) of serration / blanking (DAC code 20)
     * 540 + 96 + 540 + 96 = 1272 words (63.6 µs = 2544 bytes).
     * All segments are multiples of 4 -> exact Phase 0 closure! */
    uint16_t *vsync_words = (uint16_t *)s_vsync_line;
    int vsync_pos = 0;
    for (int i = 0; i < 540; i++) vsync_words[vsync_pos++] = get_sync_word(i);
    for (int i = 0; i < 96; i++)  vsync_words[vsync_pos++] = get_black_word(i);
    for (int i = 0; i < 540; i++) vsync_words[vsync_pos++] = get_sync_word(i);
    for (int i = 0; i < 96; i++)  vsync_words[vsync_pos++] = get_black_word(i);

    /* Standard horizontal blank line:
     * Words 0..95 (96 words = 4.8 µs): H-Sync tip (DAC code 0)
     * Words 96..1271 (1176 words = 58.8 µs): Blanking / black pedestal (DAC code 20)
     * 96 + 1176 = 1272 words (63.6 µs = 2544 bytes). */
    uint16_t *blank_words = (uint16_t *)s_blank_line;
    for (int i = 0; i < 96; i++) {
        blank_words[i] = get_sync_word(i);
    }
    for (int i = 96; i < (int)NTSC_LINE_WORDS; i++) {
        blank_words[i] = get_black_word(i - 96);
    }

    /* Initialize all 56 active text scanlines to blank line */
    for (int l = 0; l < (int)OSD_ACTIVE_LINES; l++) {
        memcpy(s_osd_lines[l], s_blank_line, NTSC_LINE_BYTES);
    }

    /* Full EIA RS-170 NTSC 240p standard 262-node circular DMA descriptor chain:
     * - Lines 0..2 (3 lines): Pre-equalizing pulses (s_eq_line)
     * - Lines 3..5 (3 lines): Vertical sync broad pulses (s_vsync_line)
     * - Lines 6..8 (3 lines): Post-equalizing pulses (s_eq_line)
     * - Lines 9..69 (61 lines): Top blank border & VBI (s_blank_line)
     * - Lines 70..181 (112 lines): Active menu text (s_osd_lines, 56 scanlines doubled)
     * - Lines 182..261 (80 lines): Bottom blank border (s_blank_line)
     * Total = 3 + 3 + 3 + 61 + 112 + 80 = 262 scanlines @ 60.012 Hz! */
    for (int i = 0; i < (int)NTSC_TOTAL_LINES; i++) {
        dma_descriptor_t *node = &s_osd_dma_nodes[i];
        node->dw0.size = NTSC_LINE_BYTES;
        node->dw0.length = NTSC_LINE_BYTES;
        node->dw0.owner = 1;
        node->dw0.suc_eof = 0;

        if (i < 3) {
            /* Lines 0..2: Pre-equalizing pulses (RS-170 standard) */
            node->buffer = s_eq_line;
        } else if (i < 6) {
            /* Lines 3..5: Vertical sync serrations (3 lines of broad pulses) */
            node->buffer = s_vsync_line;
        } else if (i < 9) {
            /* Lines 6..8: Post-equalizing pulses (RS-170 standard) */
            node->buffer = s_eq_line;
        } else if (i >= 70 && i < (int)(70 + OSD_ACTIVE_LINES * 2)) {
            /* Lines 70..181 (112 scanlines centered vertically):
             * Active menu text, each font row repeated twice for double-height readability! */
            int font_line = (i - 70) / 2;
            node->buffer = s_osd_lines[font_line];
        } else {
            /* Lines 9..69 and 182..261: Blank black lines with standard H-sync */
            node->buffer = s_blank_line;
        }

        node->next = (i < (int)NTSC_TOTAL_LINES - 1) ? &s_osd_dma_nodes[i + 1] : &s_osd_dma_nodes[0];
    }

    __asm__ __volatile__("fence rw, rw" ::: "memory");

    /* Pre-render initial menu text */
    osd_render_menu();

    /* Flush all NTSC line buffers and entire 262-node DMA descriptor chain to physical SRAM */
    sync_dma_c2m(s_eq_line, sizeof(s_eq_line));
    sync_dma_c2m(s_vsync_line, sizeof(s_vsync_line));
    sync_dma_c2m(s_blank_line, sizeof(s_blank_line));
    sync_dma_c2m(s_osd_lines, sizeof(s_osd_lines));
    sync_dma_c2m(s_osd_dma_nodes, sizeof(s_osd_dma_nodes));
}

static void osd_render_menu(void)
{
    const fpv_channel_t *ch = rf_get_current_channel();
    char buf[40];

    osd_draw_string(0, 32, "=== C5VRX-3 RECEIVER MENU ===");

    snprintf(buf, sizeof(buf), "%c [1] BAND:   %s",
             (s_menu_cursor == 0) ? '>' : ' ', rf_get_band_name(rf_get_current_band()));
    osd_draw_string(1, 32, buf);

    snprintf(buf, sizeof(buf), "%c [2] CH:     %s (%u MHz)",
             (s_menu_cursor == 1) ? '>' : ' ', ch->name, ch->freq_mhz);
    osd_draw_string(2, 32, buf);

    if (s_last_q_phase >= 40) {
        snprintf(buf, sizeof(buf), "%c [3] VTX CFO: %+4d kHz [LCK %d%%]",
             (s_menu_cursor == 2) ? '>' : ' ', s_cfo_khz, s_last_q_phase);
    } else {
        snprintf(buf, sizeof(buf), "%c [3] VTX CFO: NO SIGNAL",
                 (s_menu_cursor == 2) ? '>' : ' ');
    }
    osd_draw_string(3, 32, buf);

    snprintf(buf, sizeof(buf), "%c [4] GEAR:   %s",
             (s_menu_cursor == 3) ? '>' : ' ', s_current_bw40 ? "BW40 (COLOR)" : "BW20 (+3dB)");
    osd_draw_string(4, 32, buf);

    snprintf(buf, sizeof(buf), "%c [5] AFC:    %s",
             (s_menu_cursor == 4) ? '>' : ' ',
             (s_afc_mode == AFC_MODE_AUTO) ? "AUTO EXP (+/-1.5M)" :
             (s_afc_mode == AFC_MODE_HOLD) ? "HOLD (FROZEN)" : "OFF (0 kHz)");
    osd_draw_string(5, 32, buf);

    snprintf(buf, sizeof(buf), "%c [6] SAVE & EXIT",
             (s_menu_cursor == 5) ? '>' : ' ');
    osd_draw_string(6, 32, buf);

    sync_dma_c2m(s_osd_lines, sizeof(s_osd_lines));
}

static void video_set_menu_mode(bool active)
{
    if (s_menu_active == active) return;
    s_menu_active = active;

    if (s_tx_dscr_count <= 0 || !s_tx_dscr_nodes[s_tx_dscr_count - 1].dscr) {
        printf("[OSD] ERROR: s_tx_dscr_nodes not initialized\n");
        return;
    }

    if (active) {
        /* Pre-render fresh menu state */
        osd_render_menu();

        /* Ensure all OSD descriptors are firmly synced to physical SRAM */
        s_osd_dma_nodes[NTSC_TOTAL_LINES - 1].next = &s_osd_dma_nodes[0];
        sync_dma_c2m(s_osd_dma_nodes, sizeof(s_osd_dma_nodes));

        /* Splice OSD menu into GDMA without stopping hardware!
         * Tail of raw ring -> Head of OSD menu chain.
         * Tail of OSD menu chain -> Head of OSD menu chain (circular).
         * GDMA naturally and seamlessly steps into the NTSC 240p menu at the next ring boundary! */
        s_tx_dscr_nodes[s_tx_dscr_count - 1].dscr->next = &s_osd_dma_nodes[0];
        sync_dma_c2m(s_tx_dscr_nodes[s_tx_dscr_count - 1].dscr, sizeof(dma_descriptor_t));
        __asm__ __volatile__("fence rw, rw" ::: "memory");

        printf("[OSD] Spliced TX GDMA -> Local NTSC 240p Menu Chain (Seamless)\n");
    } else {
        /* Find current RX descriptor to guarantee safe separation upon return */
        uint32_t rx_now = (s_rx_dma_ch >= 0 && s_rx_dma_ch < 3)
                          ? AHB_DMA.channel[s_rx_dma_ch].in.in_dscr_bf0.val : 0;
        int rx_idx = find_dscr_index(s_rx_dscr_nodes, s_rx_dscr_count, rx_now);
        int safe_tx_idx = 0;
        if (rx_idx >= 0 && s_tx_dscr_count > 0) {
            safe_tx_idx = (rx_idx + (s_tx_dscr_count / 2)) % s_tx_dscr_count;
        }

        /* Splice back to raw ring at the end of the current NTSC frame */
        s_osd_dma_nodes[NTSC_TOTAL_LINES - 1].next = s_tx_dscr_nodes[safe_tx_idx].dscr;
        sync_dma_c2m(&s_osd_dma_nodes[NTSC_TOTAL_LINES - 1], sizeof(dma_descriptor_t));

        s_tx_dscr_nodes[s_tx_dscr_count - 1].dscr->next = s_tx_dscr_nodes[0].dscr;
        sync_dma_c2m(s_tx_dscr_nodes[s_tx_dscr_count - 1].dscr, sizeof(dma_descriptor_t));
        __asm__ __volatile__("fence rw, rw" ::: "memory");

        printf("[OSD] Spliced Menu -> Live Video Ring (Target TX node %d)\n", safe_tx_idx);
    }
}

static void init_boot_button(void)
{
    const gpio_config_t cfg = {
        .pin_bit_mask = 1ULL << BOOT_BTN_GPIO,
        .mode = GPIO_MODE_INPUT,
        .pull_up_en = GPIO_PULLUP_ENABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE,
    };
    gpio_config(&cfg);
}

static void handle_button_short_click(void)
{
    if (s_menu_active) {
        s_menu_cursor = (s_menu_cursor + 1) % 6;
        osd_render_menu();
        s_menu_timeout_ticks = 0;
        printf("[BTN: SHORT] Menu cursor -> %d\n", s_menu_cursor);
    } else {
        rf_cycle_channel_in_band();
        s_cfo_khz = 0;
        s_agc_state = AGC_STATE_SEARCH;
        const fpv_channel_t *ch = rf_get_current_channel();
        printf("[BTN: SHORT] Channel switched to %s (%u MHz) in %s\n",
               ch->name, ch->freq_mhz, rf_get_band_name(rf_get_current_band()));
    }
}

static void handle_button_long_click(void)
{
    if (!s_menu_active) {
        if (!s_osd_boot_btn_enabled) {
            printf("[BTN: LONG] OSD menu via BOOT button is DISABLED (Safe Flight Mode)\n");
            return;
        }
        s_menu_cursor = 0;
        s_menu_timeout_ticks = 0;
        video_set_menu_mode(true);
        printf("[BTN: LONG] OSD Menu Opened!\n");
    } else {
        switch (s_menu_cursor) {
        case 0: /* BAND */
            rf_cycle_band();
            s_cfo_khz = 0;
            s_agc_state = AGC_STATE_SEARCH;
            printf("[MENU: BAND] Switched to %s\n", rf_get_band_name(rf_get_current_band()));
            break;
        case 1: /* CHANNEL */
            rf_cycle_channel_in_band();
            s_cfo_khz = 0;
            s_agc_state = AGC_STATE_SEARCH;
            printf("[MENU: CHANNEL] Switched to %s (%u MHz)\n",
                   rf_get_current_channel()->name, rf_get_current_channel()->freq_mhz);
            break;
        case 2: /* VTX CFO AUTO-ZERO TUNE */
            if (s_last_q_phase >= 40 && s_cfo_khz != 0) {
                rf_step_frequency_offset_khz(-s_cfo_khz);
                printf("[MENU: VTX CFO] Auto-tuned offset by %d kHz to match VTX!\n", -s_cfo_khz);
            }
            break;
        case 3: /* GEAR (BW40 / BW20) */
            s_current_bw40 = !s_current_bw40;
            rf_set_analog_bandwidth(s_current_bw40);
            printf("[MENU: GEAR] Bandwidth set to %s\n", s_current_bw40 ? "BW40" : "BW20");
            break;
        case 4: /* AFC MODE */
            if (s_afc_mode == AFC_MODE_AUTO) {
                s_afc_mode = AFC_MODE_HOLD;
            } else if (s_afc_mode == AFC_MODE_HOLD) {
                s_afc_mode = AFC_MODE_OFF;
                rf_set_frequency_offset_khz(0);
            } else {
                s_afc_mode = AFC_MODE_AUTO;
            }
            printf("[MENU: AFC] Mode -> %d\n", s_afc_mode);
            break;
        case 5: /* SAVE & EXIT */
            video_set_menu_mode(false);
            printf("[BTN: LONG] OSD Menu Closed -> Live Video!\n");
            return;
        default:
            break;
        }
        osd_render_menu();
        s_menu_timeout_ticks = 0;
    }
}


static void analog_agc_task(void *arg)
{
    (void)arg;
    int settle_ticks = 0;
    int drift_counter = 0;
    int lost_counter = 0;
    int deep_fade_ticks = 0;
    int strong_signal_ticks = 0;
    int afc_ticks = 0;
    int telemetry_ticks = 0;
    uint8_t target_gain = 52u;
    int btn_ticks = 0;
    bool btn_long_fired = false;
    bool was_locked = false;

    int boot_grace_ticks = 20; /* 1.0s boot grace period (20 * 50ms): ignore reset/flash glitches */

    for (;;) {
        vTaskDelay(pdMS_TO_TICKS(50)); /* 20 Hz evaluation (every 50 ms) */

        /* 1. BOOT Button Sampling & Debounce (GPIO 28, active LOW) */
        if (boot_grace_ticks > 0) {
            boot_grace_ticks--;
            btn_ticks = 0;
            btn_long_fired = false;
        } else {
            int btn_level = gpio_get_level(BOOT_BTN_GPIO);
            if (btn_level == 0) {
                btn_ticks++;
                if (btn_ticks >= 12 && !btn_long_fired) { /* 600 ms long press */
                    btn_long_fired = true;
                    handle_button_long_click();
                }
            } else {
                if (btn_ticks > 0) {
                    if (!btn_long_fired && btn_ticks >= 2) { /* 100 - 550 ms short click (>= 2 samples) */
                        handle_button_short_click();
                    }
                    btn_ticks = 0;
                    btn_long_fired = false;
                }
            }
        }

        /* 2. OSD Inactivity Timeout (12.0s auto-exit) */
        if (s_menu_active) {
            s_menu_timeout_ticks++;
            if (s_menu_timeout_ticks >= 240) { /* 12.0s inactivity auto-exit */
                video_set_menu_mode(false);
                printf("[MENU] Inactivity timeout (12s) -> Live Video\n");
            }
            continue; /* Freeze AGC, AFC, and avoid modifying DMA memory while menu is displayed! */
        }

        /* Read a completed RX descriptor. Sampling s_raw_ring[0] directly can
         * race GDMA and create impossible mixed-window power/coherence metrics. */
        uint8_t *sample_src = get_completed_rx_sample_window(256);
        sync_dma_m2c((void *)sample_src, 256);

        static uint8_t sample_buf[256];
        memcpy(sample_buf, sample_src, sizeof(sample_buf));

        int n_clip = 0;
        int n_origin = 0;
        int n_coherent = 0;
        int sum_cross = 0;
        int sum_dot = 0;
        static uint16_t hist[129];
        memset(hist, 0, sizeof(hist));
        int8_t prev_i = 0, prev_q = 0;

        for (int i = 0; i < 256; i++) {
            uint8_t byte = sample_buf[i];
            int8_t q = (int8_t)((byte & 0x0fu) << 4) >> 4;
            int8_t in_val = (int8_t)(byte & 0xf0u) >> 4;

            if (in_val == -8 || in_val == 7 || q == -8 || q == 7) {
                n_clip++;
            }
            int p = (int)in_val * in_val + (int)q * q;
            if (p <= 4) {
                n_origin++;
            }
            if (p > 128) p = 128;
            hist[p]++;

            if (i > 0) {
                int dot = (int)in_val * (int)prev_i + (int)q * (int)prev_q;
                int signed_cross = (int)q * (int)prev_i - (int)in_val * (int)prev_q;
                int abs_cross = (signed_cross < 0) ? -signed_cross : signed_cross;

                /* Coherent FM sample: carrier power >= 8, phase delta within +-45 deg */
                if (p >= 8 && dot > 0 && abs_cross <= dot) {
                    n_coherent++;
                    sum_cross += signed_cross;
                    sum_dot += dot;
                }
            }
            prev_i = in_val;
            prev_q = q;
        }

        int cum = 0;
        int p_median = 0;
        for (int b = 0; b <= 128; b++) {
            cum += hist[b];
            if (cum >= 128) {
                p_median = b;
                break;
            }
        }
        int q_phase = (n_coherent * 100) / 255;

        s_last_p_median = p_median;
        s_last_q_phase = q_phase;
        s_last_n_clip = n_clip;
        s_last_n_origin = n_origin;

        /* Carrier Frequency Offset (CFO) Calculation:
         * Delta_f = (Cross / Dot) * (fs / 2pi) = (Cross / Dot) * 6366 kHz. */
        if (n_coherent >= 30 && sum_dot > 0) {
            int instant_cfo = (int)(((int64_t)sum_cross * 6366LL) / sum_dot);
            if (instant_cfo > 2000)  instant_cfo = 2000;
            if (instant_cfo < -2000) instant_cfo = -2000;
            s_cfo_khz = (s_cfo_khz * 7 + instant_cfo) / 8;
        }

        if (s_agc_mode == ANALOG_AGC_MANUAL) {
            target_gain = s_current_gain;
            s_shadow_gain = s_current_gain;
            goto apply_target;
        }

        /* Settle delay after gain change */
        if (settle_ticks > 0) {
            settle_ticks--;
            goto update_telemetry;
        }

        /* 2. Fast Overload Safety Rem:
         * Triggers if clipping occurs (n_clip >= 4) AND median power is elevated. */
        if (n_clip >= 4 && p_median > 18) {
            int drop = (n_clip >= 16) ? 6 : 4;
            target_gain = (target_gain > drop + 2) ? (target_gain - drop) : 2;
            s_agc_state = AGC_STATE_LEARN;
            settle_ticks = 2; /* 100 ms settle */
            drift_counter = 0;
            lost_counter = 0;
            goto apply_target;
        }

        /* 3. State Machine */
        switch (s_agc_state) {
        case AGC_STATE_SEARCH:
            /* Sensitive carrier detection: coherent phase, power, or departure from origin */
            if (q_phase >= 25 || p_median >= 8 || n_origin < 180) {
                s_agc_state = AGC_STATE_LEARN;
                drift_counter = 0;
                lost_counter = 0;
            } else {
                /* No verified carrier: stay at maximum receive gain. This also
                 * allows the BW gearbox to enter BW20 while searching, so a
                 * carrier that is only recoverable in the narrow mode can be acquired. */
                target_gain = 62u;
            }
            break;

        case AGC_STATE_LEARN:
            /* Signal too hot or clipping: step gain down */
            if (p_median > 30 || n_clip >= 3) {
                int drop = (n_clip >= 8) ? 4 : 2;
                target_gain = (target_gain > drop + 2) ? (target_gain - drop) : 2;
                settle_ticks = 1;
            }
            /* Signal weak or picture degrading: actively step gain UP towards 62 */
            else if ((p_median < 20 || q_phase < 70) && target_gain < 62u && n_clip <= 2) {
                int step = (q_phase < 45 || p_median < 14) ? 4 : 2;
                if ((int)target_gain + step <= 62) {
                    target_gain += step;
                } else {
                    target_gain = 62u;
                }
                settle_ticks = 1;
            }
            /* Optimal target zone converged */
            else {
                /* TRACK requires an actually coherent FM carrier. Reaching the
                 * gain ceiling alone is never evidence of lock. */
                if (n_clip <= 2 && q_phase >= 65) {
                    s_agc_state = AGC_STATE_TRACK;
                    drift_counter = 0;
                    lost_counter = 0;
                }
            }
            break;

        case AGC_STATE_TRACK:
            /* Check for total carrier loss: 500 ms persistent loss */
            if (q_phase < 28 && p_median < 14) {
                lost_counter++;
                if (lost_counter >= 10) { /* ~500 ms persistent loss */
                    s_agc_state = AGC_STATE_SEARCH;
                    lost_counter = 0;
                    break;
                }
            } else {
                lost_counter = 0;
            }

            /* Check for signal quality degradation or overload:
             * 1. Needs boost: picture is getting noisy (Q_phase < 68% or P_median < 18)
             *    while not at maximum gain and not clipping.
             * 2. Needs cut: signal too hot (P_median > 30 or clipping). */
            bool needs_gain_boost = (q_phase < 68 || p_median < 18) && (target_gain < 62u) && (n_clip <= 2);
            bool needs_gain_cut   = (p_median > 30) || (n_clip >= 3);

            if (needs_gain_boost || needs_gain_cut) {
                drift_counter++;
                if (drift_counter >= 3) { /* Persistent for 150 ms */
                    s_agc_state = AGC_STATE_LEARN;
                    drift_counter = 0;
                }
            } else {
                drift_counter = 0;
                /* Inside deadband: 100% frozen, ZERO register writes */
            }
            break;
        }

apply_target:
        s_shadow_gain = target_gain;
        if (s_agc_mode == ANALOG_AGC_ACTIVE) {
            if (target_gain != s_current_gain) {
                uint8_t old_g = s_current_gain;
                s_current_gain = target_gain;
                rf_set_rx_gain(true, s_current_gain);
                printf("[AGC:GAIN] %u -> %u (P_med=%d, Q_phase=%d%%, Clip=%d, State=%s)\n",
                       old_g, s_current_gain, p_median, q_phase, n_clip,
                       (s_agc_state == AGC_STATE_TRACK) ? "TRACK" :
                       (s_agc_state == AGC_STATE_LEARN) ? "LEARN" : "SRCH");
            }
        }

        /* 4. Dynamic Bandwidth Gearbox (BW40 High Gear <-> BW20 Long-Range Survival) */
        if (s_bw_gear_mode == BW_GEAR_AUTO) {
            if (s_current_bw40) {
                /* In BW40: downshift to BW20 if entering deep fade / severe starvation */
                if (s_current_gain >= 56u && (q_phase < 55 || p_median < 16)) {
                    deep_fade_ticks++;
                    if (deep_fade_ticks >= 4) { /* Persisted for 200 ms */
                        s_current_bw40 = false;
                        rf_set_analog_bandwidth(false); /* DOWNSHIFT to BW20 (+3 dB boost!) */
                        printf("[GEARBOX] DOWNSHIFT -> BW20 (+3 dB SNR boost for deep fade)\n");
                        deep_fade_ticks = 0;
                        strong_signal_ticks = 0;
                        settle_ticks = 2;
                    }
                } else {
                    deep_fade_ticks = 0;
                }
            } else {
                /* In BW20: upshift to BW40 if signal strongly recovered */
                if (p_median >= 22 && q_phase >= 75) {
                    strong_signal_ticks++;
                    if (strong_signal_ticks >= 20) { /* Persisted continuously for 1.0s */
                        s_current_bw40 = true;
                        rf_set_analog_bandwidth(true); /* UPSHIFT to BW40 (restore full color!) */
                        printf("[GEARBOX] UPSHIFT -> BW40 (Signal recovered, full color restored)\n");
                        strong_signal_ticks = 0;
                        deep_fade_ticks = 0;
                        settle_ticks = 2;
                    }
                } else {
                    strong_signal_ticks = 0;
                }
            }
        } else if (s_bw_gear_mode == BW_GEAR_BW40) {
            if (!s_current_bw40) {
                s_current_bw40 = true;
                rf_set_analog_bandwidth(true);
            }
        } else if (s_bw_gear_mode == BW_GEAR_BW20) {
            if (s_current_bw40) {
                s_current_bw40 = false;
                rf_set_analog_bandwidth(false);
            }
        }

        /* 5. Experimental AFC.
         * Default is OFF: mean WBFM phase slope over a 6.4 us window includes
         * video modulation and is NOT a calibrated absolute carrier offset.
         * AUTO remains an explicit test mode only. */
        if (s_afc_mode == AFC_MODE_AUTO) {
            /* Only adjust if carrier is strongly locked (Q_phase >= 75%) and gain settled */
            if (q_phase >= 75 && p_median >= 18 && settle_ticks == 0) {
                /* Centering deadband: +/- 35 kHz. Inside deadband = 0 register writes */
                if (s_cfo_khz > 35 || s_cfo_khz < -35) {
                    afc_ticks++;
                    if (afc_ticks >= 20) { /* Persisted for 1.0 second */
                        int cur_offset = rf_get_frequency_offset_khz();
                        int target_offset = cur_offset + s_cfo_khz;
                        rf_set_frequency_offset_khz(target_offset);
                        afc_ticks = 0;
                        settle_ticks = 2;
                    }
                } else {
                    afc_ticks = 0;
                }
            } else {
                afc_ticks = 0; /* Frozen during noise or deep fades: NO drifting away! */
            }
        } else if (s_afc_mode == AFC_MODE_OFF) {
            if (rf_get_frequency_offset_khz() != 0) {
                rf_set_frequency_offset_khz(0);
            }
        }

        /* 6. Transient Carrier Lock Detection */
        bool is_locked = (s_agc_state == AGC_STATE_TRACK) && (q_phase >= 55);
        if (is_locked && !was_locked) {
            const fpv_channel_t *ch = rf_get_current_channel();
            printf("[CARRIER] Locked on %s (%u MHz) in %s (P_med=%d, Q_phase=%d%%, G=%u)\n",
                   ch->name, ch->freq_mhz, rf_get_band_name(rf_get_current_band()),
                   p_median, q_phase, s_current_gain);
        }
        was_locked = is_locked;


update_telemetry:
        telemetry_ticks++;
        if (telemetry_ticks >= 20) { /* 1 Hz periodic telemetry log */
            telemetry_ticks = 0;
            const fpv_channel_t *ch = rf_get_current_channel();
            int cur_off = rf_get_frequency_offset_khz();
            int total_khz = (int)ch->freq_mhz * 1000 + cur_off;
            printf("[AGC:%s] %-5s BW=%-4s | %s:%d.%03dMHz %+4dkHz (CFO=%+4d kHz) | G=%u | P=%-2d Q=%2d%% | c=%-2d\n",
                   (s_agc_mode == ANALOG_AGC_ACTIVE) ? "ACT" :
                   (s_agc_mode == ANALOG_AGC_SHADOW) ? "SHD" : "MAN",
                   (s_agc_state == AGC_STATE_TRACK) ? "TRACK" :
                   (s_agc_state == AGC_STATE_LEARN) ? "LEARN" : "SRCH",
                   s_current_bw40 ? "BW40" : "BW20",
                   ch->name,
                   total_khz / 1000,
                   (total_khz % 1000 >= 0 ? total_khz % 1000 : -(total_khz % 1000)),
                   cur_off,
                   s_cfo_khz,
                   s_current_gain,
                   s_last_p_median, s_last_q_phase, s_last_n_clip);
            fflush(stdout);
        }
    }
}

static void console_diag_task(void *arg)
{
    (void)arg;
    for (;;) {
        int c = getchar();
        if (c != EOF && c > 0) {
            if (c == '+' || c == 'k') {
                s_agc_mode = ANALOG_AGC_MANUAL;
                if (s_current_gain < 62u) s_current_gain += 2u;
                rf_set_rx_gain(true, s_current_gain);
                printf("[MANUAL GAIN] = %u (reg=0x%08lx)\n", s_current_gain, (unsigned long)rf_get_rx_gain_reg());
            } else if (c == '-' || c == 'j') {
                s_agc_mode = ANALOG_AGC_MANUAL;
                if (s_current_gain >= 2u) s_current_gain -= 2u;
                rf_set_rx_gain(true, s_current_gain);
                printf("[MANUAL GAIN] = %u (reg=0x%08lx)\n", s_current_gain, (unsigned long)rf_get_rx_gain_reg());
            } else if (c == 'a') {
                s_agc_mode = ANALOG_AGC_ACTIVE;
                printf("[AGC MODE] -> ACTIVE (Self-Calibrating Adaptive Gain Controller ACTIVE)\n");
            } else if (c == 's') {
                s_agc_mode = ANALOG_AGC_SHADOW;
                printf("[AGC MODE] -> SHADOW (Dry-run: RF gain frozen at %u, computing recommendations)\n", s_current_gain);
            } else if (c == 'm') {
                s_agc_mode = ANALOG_AGC_MANUAL;
                printf("[AGC MODE] -> MANUAL (Fixed gain=%u)\n", s_current_gain);
            } else if (c == 'b') {
                if (s_bw_gear_mode == BW_GEAR_AUTO) {
                    s_bw_gear_mode = BW_GEAR_BW40;
                    s_current_bw40 = true;
                    rf_set_analog_bandwidth(true);
                    printf("[BW GEAR] -> FORCED BW40 (Full color / 20 MHz baseband)\n");
                } else if (s_bw_gear_mode == BW_GEAR_BW40) {
                    s_bw_gear_mode = BW_GEAR_BW20;
                    s_current_bw40 = false;
                    rf_set_analog_bandwidth(false);
                    printf("[BW GEAR] -> FORCED BW20 (+3 dB SNR Long-Range Survival mode)\n");
                } else {
                    s_bw_gear_mode = BW_GEAR_AUTO;
                    printf("[BW GEAR] -> AUTO GEARBOX (Dynamic Bandwidth Adaptation)\n");
                }
            } else if (c == 'c') {
                rf_cycle_channel_in_band();
                const fpv_channel_t *ch = rf_get_current_channel();
                s_cfo_khz = 0;
                s_agc_state = AGC_STATE_SEARCH;
                printf("[CHANNEL] Switched to %s (%u MHz) in %s\n",
                       ch->name, ch->freq_mhz, rf_get_band_name(rf_get_current_band()));
            } else if (c == 'C') {
                rf_cycle_band();
                const fpv_channel_t *ch = rf_get_current_channel();
                s_cfo_khz = 0;
                s_agc_state = AGC_STATE_SEARCH;
                printf("[BAND] Switched to %s - Channel %s (%u MHz)\n",
                       rf_get_band_name(rf_get_current_band()), ch->name, ch->freq_mhz);
            } else if (c == 'f') {
                if (s_afc_mode == AFC_MODE_AUTO) {
                    s_afc_mode = AFC_MODE_HOLD;
                    printf("[AFC] -> HOLD (Current offset %+d kHz frozen)\n", rf_get_frequency_offset_khz());
                } else if (s_afc_mode == AFC_MODE_HOLD) {
                    s_afc_mode = AFC_MODE_OFF;
                    rf_set_frequency_offset_khz(0);
                    printf("[AFC] -> OFF (Offset reset to 0 kHz)\n");
                } else {
                    s_afc_mode = AFC_MODE_AUTO;
                    printf("[AFC] -> AUTO EXPERIMENTAL (uncalibrated WBFM bias estimator)\n");
                }
            } else if (c == ',' || c == '<') {
                rf_step_frequency_offset_khz(-50);
                int off = rf_get_frequency_offset_khz();
                int tot = (int)rf_get_current_channel()->freq_mhz * 1000 + off;
                printf("[FINE TUNE] Offset = %+d kHz (Tuned: %d.%03d MHz)\n",
                       off, tot / 1000, (tot % 1000 >= 0 ? tot % 1000 : -(tot % 1000)));
            } else if (c == '.' || c == '>') {
                rf_step_frequency_offset_khz(+50);
                int off = rf_get_frequency_offset_khz();
                int tot = (int)rf_get_current_channel()->freq_mhz * 1000 + off;
                printf("[FINE TUNE] Offset = %+d kHz (Tuned: %d.%03d MHz)\n",
                       off, tot / 1000, (tot % 1000 >= 0 ? tot % 1000 : -(tot % 1000)));
            } else if (c == '0') {
                rf_set_frequency_offset_khz(0);
                printf("[FINE TUNE] Offset reset to +0 kHz\n");
            } else if (c == 'e') {
                PARL_IO.rx_clk_cfg.rx_clk_i_inv = !PARL_IO.rx_clk_cfg.rx_clk_i_inv;
                printf("[EDGE] RX SAMPLE EDGE TOGGLED -> %s (rx_clk_i_inv=%d)\n",
                       PARL_IO.rx_clk_cfg.rx_clk_i_inv ? "NEG" : "POS",
                       (int)PARL_IO.rx_clk_cfg.rx_clk_i_inv);
            } else if (c == 'o') {
                video_set_menu_mode(!s_menu_active);
                printf("[OSD] Menu %s via console\n", s_menu_active ? "OPENED" : "CLOSED");
            } else if (c == 'O') {
                s_osd_boot_btn_enabled = !s_osd_boot_btn_enabled;
                printf("[OSD] BOOT button menu trigger -> %s\n",
                       s_osd_boot_btn_enabled ? "ENABLED (Long-press BOOT enters menu)" : "DISABLED (Safe Flight Mode)");
            } else if (s_menu_active && (c == ' ' || c == 'n')) {
                s_menu_cursor = (s_menu_cursor + 1) % 6;
                osd_render_menu();
                s_menu_timeout_ticks = 0;
                printf("[MENU] Cursor -> %d\n", s_menu_cursor);
            } else if (s_menu_active && (c == '\r' || c == '\n' || c == 'x')) {
                handle_button_long_click();
            } else {
                uint32_t rx_dscr = 0, tx_dscr = 0;
                uint32_t rx_off = get_rx_dma_offset(&rx_dscr);
                uint32_t tx_off = get_tx_dma_offset(&tx_dscr);
                uint32_t dist = (rx_off >= tx_off) ? (rx_off - tx_off) : (sizeof(s_raw_ring) - tx_off + rx_off);
                int rx_nodes = patch_descriptors_clear_eof(s_rx_dma_ch, true);
                int tx_nodes = patch_descriptors_clear_eof(s_tx_dma_ch, false);
                const fpv_channel_t *ch = rf_get_current_channel();
                int off = rf_get_frequency_offset_khz();
                int tot = (int)ch->freq_mhz * 1000 + off;

                printf("\n=======================================================\n");
                printf(" C5VRX-3 REALTIME RECEPTION & FREQUENCY DIAGNOSTICS\n");
                printf(" Receiver Channel:           %s (%u MHz)\n", ch->name, ch->freq_mhz);
                printf(" Tuned Frequency:            %d.%03d MHz (Offset: %+d kHz)\n",
                       tot / 1000, (tot % 1000 >= 0 ? tot % 1000 : -(tot % 1000)), off);
                printf(" Carrier Frequency Offset:   %+d kHz (VTX %s)\n",
                       s_cfo_khz, (s_cfo_khz > 20) ? "high" : (s_cfo_khz < -20) ? "low" : "centered");
                printf(" AFC Mode:                   %s\n",
                       (s_afc_mode == AFC_MODE_AUTO) ? "AUTO EXPERIMENTAL (uncalibrated estimator)" :
                       (s_afc_mode == AFC_MODE_HOLD) ? "HOLD (Offset Frozen)" : "OFF (0 kHz)");
                printf(" Bandwidth Gear:             %s (Current: %s)\n",
                       (s_bw_gear_mode == BW_GEAR_AUTO) ? "AUTO (Dynamic Adaptation)" :
                       (s_bw_gear_mode == BW_GEAR_BW40) ? "FORCED BW40" : "FORCED BW20",
                       s_current_bw40 ? "BW40 (Wide / Color)" : "BW20 (Narrow / +3 dB Survival)");
                printf(" Adaptive AGC Mode:          %s (State=%s)\n",
                       (s_agc_mode == ANALOG_AGC_ACTIVE) ? "ACTIVE" :
                       (s_agc_mode == ANALOG_AGC_SHADOW) ? "SHADOW (Safe Dry-Run)" : "MANUAL",
                       (s_agc_state == AGC_STATE_TRACK) ? "TRACK" :
                       (s_agc_state == AGC_STATE_LEARN) ? "LEARN" : "SEARCH");
                printf(" Gain Settings:              G_actual=%u, G_shadow_rec=%u (reg=0x%08lx)\n",
                       s_current_gain, s_shadow_gain, (unsigned long)rf_get_rx_gain_reg());
                printf(" FM Vector Metrics:          P_median=%d, Q_phase=%d%%, Clip=%d, Origin=%d\n",
                       s_last_p_median, s_last_q_phase, s_last_n_clip, s_last_n_origin);
                printf(" GDMA Ring:                  dist=%lu (rx_off=%lu, tx_off=%lu)\n",
                       (unsigned long)dist, (unsigned long)rx_off, (unsigned long)tx_off);
                printf(" Zero-EOF Status:            RX patched=%d nodes, TX patched=%d nodes\n",
                       rx_nodes, tx_nodes);
                printf(" PARLIO TX Underflows:       %lu (Zero underflows)\n",
                       (unsigned long)s_hw_counters.parl_tx_rempty_count);
                printf(" RX Sample Edge:             %s (rx_clk_i_inv=%d)\n",
                       PARL_IO.rx_clk_cfg.rx_clk_i_inv ? "NEG" : "POS",
                       (int)PARL_IO.rx_clk_cfg.rx_clk_i_inv);
                printf(" OSD Menu Status:            %s (BOOT button trigger: %s)\n",
                       s_menu_active ? "OPEN" : "CLOSED",
                       s_osd_boot_btn_enabled ? "ENABLED" : "DISABLED (Safe Flight Mode)");
                printf(" Keys:\n");
                printf("  'a'/'s'/'m': AGC mode (active / shadow / manual)\n");
                printf("  '+' / '-':   Manual gain step (+/-2)\n");
                printf("  'b':         Bandwidth gear (auto / forced bw40 / forced bw20)\n");
                printf("  'c':         Cycle FPV channel (A1..A8, R1..R8, B1..B8, F1..F8)\n");
                printf("  'f':         AFC mode (auto-centering / hold / off)\n");
                printf("  ',' / '.':   Fine-tune offset (-50 / +50 kHz)\n");
                printf("  '0':         Reset offset to 0 kHz\n");
                printf("  'e':         Toggle RX sample edge (POS/NEG)\n");
                printf("  'o':         Toggle OSD Menu via console\n");
                printf("  'O':         Toggle BOOT button menu trigger (Safe Flight Mode)\n");
                printf("  'd':         Print this diagnostic summary\n");
                printf("=======================================================\n\n");
            }
            fflush(stdout);
        }
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}


/* ----- Main entry point ----- */

esp_err_t video_start(void)
{
    /* Initialize BOOT button on GPIO 28 */
    init_boot_button();

    /* Initialize NTSC 240p OSD buffers and 262-node DMA descriptor chain */
    osd_init_buffers();

    /* Zero the ring before starting. Flush to DMA-visible SRAM. */
    memset(s_raw_ring, 0, sizeof(s_raw_ring));
    sync_dma_c2m(s_raw_ring, sizeof(s_raw_ring));

    esp_err_t err;

    if ((err = prepare_rx()) != ESP_OK) return err;
    if ((err = prepare_tx()) != ESP_OK) return err;

    /* Start RX cyclic ring. GDMA begins writing at s_raw_ring[0]. */
    if ((err = start_rx()) != ESP_OK) return err;

    /* Put PARLIO RX into pure continuous hardware mode:
     * 1. Disable all GDMA RX channel interrupts so the CPU is never interrupted
     *    (~9,775 ISRs/sec eliminated!).
     * 2. Set rx_eof_gen_sel = 1 (external enable, non-existent in soft mode)
     *    so PARLIO RX never generates an EOF stall event.
     * This matches PARLIO TX's unbroken hardware loop, eliminating pointer drift! */
    AHB_DMA.in_intr[0].ena.val = 0;
    AHB_DMA.in_intr[1].ena.val = 0;
    AHB_DMA.in_intr[2].ena.val = 0;
    PARL_IO.rx_genrl_cfg.rx_eof_gen_sel = 1;

    /* Establish producer/consumer separation before starting TX.
     * In 16 KiB ring (16384 bytes, 4 full 4092-byte descriptors D0..D3 + 16-byte tail D4):
     * Delay by exactly 8192 bytes (2 full descriptors = 204.8 µs).
     * This places TX at D0 while RX is at D2, leaving D1 sitting safely between them.
     * RX has demonstrably finished D1 (>100 µs ago), and TX has not yet reached D1 (>100 µs away).
     * D1 is 100% safe for OSD overlay! */
    esp_rom_delay_us(8192u * 1000000u / IQ_RATE_HZ);

    if ((err = start_tx()) != ESP_OK) return err;

    /* Discover AHB_DMA channels assigned to PARL_IO (peripheral ID 9) */
    for (int i = 0; i < 3; i++) {
        if (AHB_DMA.channel[i].in.in_peri_sel.peri_in_sel_chn == 9) {
            s_rx_dma_ch = i;
        }
        if (AHB_DMA.channel[i].out.out_peri_sel.peri_out_sel_chn == 9) {
            s_tx_dma_ch = i;
        }
    }

    /* Clear suc_eof on ALL GDMA descriptors for both RX and TX to eliminate
     * hardware wrap EOF bubbles completely! The buffer becomes a truly infinite ring. */
    int rx_nodes = patch_descriptors_clear_eof(s_rx_dma_ch, true);
    int tx_nodes = patch_descriptors_clear_eof(s_tx_dma_ch, false);

    /* Start interactive console for on-demand diagnostics (zero periodic CPU/bus traffic) */
    xTaskCreate(console_diag_task, "console_diag", 3072, NULL, 1, NULL);

    /* Start dedicated Analog Video AGC engine (P_median in [20, 30], fast attack) */
    xTaskCreate(analog_agc_task, "analog_agc", 8192, NULL, 3, NULL);


    /* Print startup stamp (visible on serial monitor at boot). */
    ESP_EARLY_LOGW(TAG,
        "\n=======================================================\n"
        " C5VRX-3  Seamless 16K Phase5 receiver (Zero-EOF Circular GDMA)\n"
        " Clock:   PARLIO_CLK_SRC_DEFAULT 40MHz (SPLL internal)\n"
        " Telemetry: Live GDMA ring pointer tracking (rx_ch=%d, tx_ch=%d)\n"
        " Buffer:  16,384 bytes cyclic ring (Zero-EOF patched: RX=%d TX=%d)\n"
        " RX:      40 MS/s POS edge, 16,384 bytes pure HW cyclic GDMA\n"
        " Demod:   Phase5 50ns / P%u / G%u / current-minus-previous\n"
        " TX:      40 MHz [D,D] / eof=downstream / tail=0\n"
        " Lock:    GDMA ISRs disabled, RX EOF disabled, suc_eof=0 cleared\n"
        " CPU:     done (hardware runs in unbroken infinite loop)\n"
        "=======================================================\n",
        s_rx_dma_ch, s_tx_dma_ch, rx_nodes, tx_nodes, DAC_IDLE_CODE, 2u);

    return ESP_OK;
}
