/**
 * video.c - Realtime MODEM_DIAG -> PARLIO RX -> 16K ring -> Phase5 TX -> DAC.
 *
 * Implements the complete production datapath for C5VRX-3:
 *
 *   MODEM_DIAG full Q4/I4 @ 40 MS/s
 *     -> PARLIO RX POS edge @ 40 MHz
 *     -> 16 KiB cyclic raw DMA ring (HP SRAM)
 *     -> PARLIO TX @ 40 MHz + Phase5 TX BitScrambler (fm.bsasm)
 *     -> [D,D] 6-bit CVBS @ 20 MS/s unique / 40 MHz DAC clock
 *     -> 6-bit resistor DAC
 *
 * Reference: Seamless Golden 16K (build-golden-notel) -- proven best live build.
 *
 * Fixed production constants (NOT configurable at runtime):
 *   IQ rate:        40 MHz
 *   DAC rate:       40 MHz physical ([D,D] = 20 MS/s unique CVBS)
 *   Ring:           16384 bytes (HP SRAM, DMA-aligned)
 *   Pedestal:       20   (hardcoded in FM LUT)
 *   Gain:           2    (hardcoded in FM LUT)
 *   Polarity:       current-minus-previous (hardcoded in FM LUT)
 *   RX sample edge: POS
 *   TX shift edge:  NEG
 *   BS EOF:         downstream (PARLIO TX loop never generates downstream EOF)
 *   BS tail:        0 bytes
 *
 * After video_start() the CPU has nothing to do. No periodic tasks or timers.
 */

#include "video.h"
#include "rf.h"

#include <stdint.h>
#include <string.h>

#include "driver/bitscrambler.h"
#include "driver/gpio.h"
#include "driver/parlio_bitscrambler.h"
#include "driver/parlio_rx.h"
#include "driver/parlio_tx.h"
#include "esp_attr.h"
#include "esp_cache.h"
#include "esp_log.h"
#include "esp_rom_sys.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "soc/parl_io_struct.h"
#include "soc/bitscrambler_struct.h"
#include "soc/ahb_dma_struct.h"
#include "soc/pcr_struct.h"
#include "modem/modem_syscon_reg.h"
#include "hal/dma_types.h"
#include "esp_clock_output.h"

/* Hardware diagnostic counters in IRAM to measure transport hiccups without printf spam */
typedef struct {
    uint32_t parl_rx_wovf_count;
    uint32_t parl_tx_rempty_count;
    uint32_t parl_tx_eof_count;
    uint32_t bs_fifo_empty_count;
    uint32_t bs_eof_overload_count;
    uint32_t checks;
} hw_transport_counters_t;

static volatile hw_transport_counters_t s_hw_counters;

/* fm.bsasm program symbol generated by target_bitscrambler_add_src(). */
BITSCRAMBLER_PROGRAM(s_fm_program, "fm");

/* ----- Fixed production constants ----- */
#define IQ_RATE_HZ       40000000u   /* MODEM_DIAG / PARLIO RX clock */
#define DAC_RATE_HZ      40000000u   /* PARLIO TX clock ([D,D] = 20 MS/s unique) */
#define RAW_RING_BYTES   32768u      /* 32768 byte cyclic ring (32 KiB standard) */
#define DAC_IDLE_CODE    20u         /* Pedestal 20 (sync tip level) */

/* TX GPIO mapping: 6-bit resistor DAC.
 * Order: DAC bit 0 (LSB) .. DAC bit 5 (MSB) on data_gpio_nums[0..5].
 * Bits 6..7 unused (set to -1).
 * Verified against C5VRX-2 realtime.c (standard 8-bit PARLIO TX, non-parlio4). */
static const int s_dac_gpio[8] = {23, 24, 11, 12, 8, 9, -1, -1};

_Static_assert(IQ_RATE_HZ == 40000000u, "IQ rate must be 40 MHz");
_Static_assert(DAC_RATE_HZ == 40000000u, "DAC rate must be 40 MHz");
_Static_assert(RAW_RING_BYTES == 32768u, "Ring must be exactly 32768 bytes");

static const char *TAG = "c5vrx3_video";

/* DMA-aligned ring buffer in HP SRAM.
 * RX GDMA writes at 40 MB/s; TX GDMA reads at 40 MB/s.
 * TX starts one block (4096 bytes = 102.4 µs) behind RX; they share
 * PLL_F240M/6, so separation cannot drift during normal operation. */
static DMA_ATTR __attribute__((aligned(64))) uint8_t s_raw_ring[RAW_RING_BYTES];

static parlio_rx_unit_handle_t      s_rx;
static parlio_rx_delimiter_handle_t s_rx_delimiter;
static parlio_tx_unit_handle_t      s_tx;

/* ----- PARLIO RX setup ----- */

static esp_err_t prepare_rx(void)
{
    /* Proven PARLIO RX config with clean internal SPLL clock */
    const parlio_rx_unit_config_t cfg = {
        .trans_queue_depth = 1u,
        .max_recv_size     = sizeof(s_raw_ring),
        .dma_burst_size    = 32u,
        .data_width        = 8u,
        .clk_src           = PARLIO_CLK_SRC_DEFAULT,
        .ext_clk_freq_hz   = 0u,
        .exp_clk_freq_hz   = IQ_RATE_HZ,
        .clk_in_gpio_num   = -1,
        .clk_out_gpio_num  = -1,
        .valid_gpio_num    = -1,
        /* GPIO order must match s_iq_pins[] in rf.c:
         * Q[9:6] on GPIO 1,0,25,7 then I[9:6] on GPIO 10,5,3,4. */
        .data_gpio_nums    = {
            GPIO_NUM_1, GPIO_NUM_0, GPIO_NUM_25, GPIO_NUM_7,
            GPIO_NUM_10, GPIO_NUM_5, GPIO_NUM_3, GPIO_NUM_4,
        },
        .flags = {
            .free_clk    = true,   /* RX clock is derived from PHY, not gated */
            .clk_gate_en = false,
            .allow_pd    = false,
        },
    };
    esp_err_t err = parlio_new_rx_unit(&cfg, &s_rx);
    if (err != ESP_OK) return err;

    /* Soft delimiter in infinite (partial_rx_en) mode.
     * POS sample edge -- proven correct for internal clock. */
    const parlio_rx_soft_delimiter_config_t delim_cfg = {
        .sample_edge  = PARLIO_SAMPLE_EDGE_POS,
        .bit_pack_order = PARLIO_BIT_PACK_ORDER_LSB,
        .eof_data_len = sizeof(s_raw_ring),
        .timeout_ticks = 0u,
    };
    err = parlio_new_rx_soft_delimiter(&delim_cfg, &s_rx_delimiter);
    if (err != ESP_OK) return err;

    return parlio_rx_unit_enable(s_rx, false);
}

/* ----- PARLIO TX setup ----- */

static esp_err_t prepare_tx(void)
{
    /* Proven PARLIO TX config from Seamless Golden 16K reference.
     * 8-bit data width, 40 MHz output, NEG shift edge, LSB packing.
     * BitScrambler decorated on the TX unit (not RX -- C5 has one BS). */
    const parlio_tx_unit_config_t cfg = {
        .clk_src              = PARLIO_CLK_SRC_DEFAULT,
        .clk_in_gpio_num      = -1,
        .input_clk_src_freq_hz = 0u,
        .output_clk_freq_hz   = DAC_RATE_HZ,
        .data_width           = 8u,
        .data_gpio_nums       = {
            s_dac_gpio[0], s_dac_gpio[1], s_dac_gpio[2], s_dac_gpio[3],
            s_dac_gpio[4], s_dac_gpio[5], s_dac_gpio[6], s_dac_gpio[7],
        },
        .clk_out_gpio_num  = -1,
        .valid_gpio_num    = -1,
        .valid_start_delay = 0,
        .valid_stop_delay  = 0,
        .trans_queue_depth = 1u,
        .max_transfer_size = sizeof(s_raw_ring),
        .dma_burst_size    = 32u,
        .shift_edge        = PARLIO_SHIFT_EDGE_NEG,   /* FIXED: NEG (RX is POS) */
        .bit_pack_order    = PARLIO_BIT_PACK_ORDER_LSB,
    };
    esp_err_t err = parlio_new_tx_unit(&cfg, &s_tx);
    if (err != ESP_OK) return err;

    /* Decorate TX with BitScrambler (TX-only; C5 has one shared BS core). */
    err = parlio_tx_unit_decorate_bitscrambler(s_tx);
    if (err != ESP_OK) return err;

    return parlio_tx_unit_enable(s_tx);
}

/* ----- Start RX cyclic ring ----- */

static esp_err_t start_rx(void)
{
    esp_err_t err = parlio_rx_soft_delimiter_start_stop(s_rx, s_rx_delimiter, true);
    if (err != ESP_OK) return err;
    const parlio_receive_config_t cfg = {
        .delimiter = s_rx_delimiter,
        .flags = {
            .partial_rx_en   = true,
            .indirect_mount  = false,
        },
    };
    return parlio_rx_unit_receive(s_rx, s_raw_ring, sizeof(s_raw_ring), &cfg);
}

/* ----- Start TX loop ----- */

static esp_err_t start_tx(void)
{
    /* Phase5 LUT is embedded in fm.bsasm -- no runtime bitscrambler_load_lut().
     * Hardware oracle v9 proved embedded LUT is byte-exact at 20 MS/s;
     * a separately preloaded LUT is NOT retained by the active PARLIO TX run. */
    const parlio_transmit_config_t cfg = {
        .idle_value          = DAC_IDLE_CODE,
        .bitscrambler_program = s_fm_program,
        .flags.loop_transmission = true,  /* Infinite -- never generates downstream EOF */
    };
    /* TX reads sizeof(s_raw_ring) * 8 bits, then loops.
     * loop_transmission=true means PARLIO TX never stops; the BitScrambler
     * with eof_on=downstream therefore runs uninterrupted forever. */
    return parlio_tx_unit_transmit(s_tx, s_raw_ring,
                                   sizeof(s_raw_ring) * 8u, &cfg);
}

static int s_rx_dma_ch = -1;
static int s_tx_dma_ch = -1;

static inline uint32_t get_rx_dma_offset(uint32_t *out_dscr_addr)
{
    if (s_rx_dma_ch < 0 || s_rx_dma_ch >= 3) return 0;
    uint32_t dscr_addr = AHB_DMA.channel[s_rx_dma_ch].in.in_dscr_bf0.val;
    if (out_dscr_addr) *out_dscr_addr = dscr_addr;
    if (dscr_addr >= 0x40800000u && dscr_addr < 0x40860000u) {
        dma_descriptor_t *dscr = (dma_descriptor_t *)(uintptr_t)dscr_addr;
        uint8_t *buf = (uint8_t *)dscr->buffer;
        if (buf >= s_raw_ring && buf < s_raw_ring + sizeof(s_raw_ring)) {
            return (uint32_t)(buf - s_raw_ring);
        }
    }
    return 0;
}

static inline uint32_t get_tx_dma_offset(uint32_t *out_dscr_addr)
{
    if (s_tx_dma_ch < 0 || s_tx_dma_ch >= 3) return 0;
    uint32_t dscr_addr = AHB_DMA.channel[s_tx_dma_ch].out.out_dscr_bf0.val;
    if (out_dscr_addr) *out_dscr_addr = dscr_addr;
    if (dscr_addr >= 0x40800000u && dscr_addr < 0x40860000u) {
        dma_descriptor_t *dscr = (dma_descriptor_t *)(uintptr_t)dscr_addr;
        uint8_t *buf = (uint8_t *)dscr->buffer;
        if (buf >= s_raw_ring && buf < s_raw_ring + sizeof(s_raw_ring)) {
            return (uint32_t)(buf - s_raw_ring);
        }
    }
    return 0;
}

static int patch_descriptors_clear_eof(int dma_ch, bool is_rx)
{
    if (dma_ch < 0 || dma_ch >= 3) return 0;
    uint32_t first_addr = is_rx ? AHB_DMA.channel[dma_ch].in.in_dscr_bf0.val
                                : AHB_DMA.channel[dma_ch].out.out_dscr_bf0.val;
    if (first_addr < 0x40800000u || first_addr >= 0x40860000u) return 0;

    dma_descriptor_t *curr = (dma_descriptor_t *)(uintptr_t)first_addr;
    int count = 0;
    while (curr && count < 64) {
        curr->dw0.suc_eof = 0;
        (void)esp_cache_msync(curr, sizeof(dma_descriptor_t), ESP_CACHE_MSYNC_FLAG_DIR_C2M);
        curr = curr->next;
        count++;
        if ((uintptr_t)curr == first_addr) break;
    }
    __asm__ __volatile__("fence rw, rw" ::: "memory");
    return count;
}

static uint8_t s_forced_gain = 24u;
static bool s_gain_forced = false;

static void console_diag_task(void *arg)
{
    (void)arg;
    for (;;) {
        int c = getchar();
        if (c != EOF && c > 0) {
            if (c == '+' || c == 'k') {
                if (s_forced_gain < 63u) s_forced_gain += 2u;
                s_gain_forced = true;
                rf_set_rx_gain(true, s_forced_gain);
                printf("[GAIN] FORCED GAIN = %u (reg=0x%08lx)\n", s_forced_gain, (unsigned long)rf_get_rx_gain_reg());
            } else if (c == '-' || c == 'j') {
                if (s_forced_gain >= 2u) s_forced_gain -= 2u;
                s_gain_forced = true;
                rf_set_rx_gain(true, s_forced_gain);
                printf("[GAIN] FORCED GAIN = %u (reg=0x%08lx)\n", s_forced_gain, (unsigned long)rf_get_rx_gain_reg());
            } else if (c == 'a') {
                s_gain_forced = false;
                rf_set_rx_gain(false, 0);
                printf("[GAIN] AUTO GAIN RESTORED (reg=0x%08lx)\n", (unsigned long)rf_get_rx_gain_reg());
            } else if (c == 'f') {
                s_gain_forced = !s_gain_forced;
                rf_set_rx_gain(s_gain_forced, s_forced_gain);
                printf("[GAIN] TOGGLE FORCED=%d (idx=%u, reg=0x%08lx)\n", s_gain_forced, s_forced_gain, (unsigned long)rf_get_rx_gain_reg());
            } else if (c == 'e') {
                PARL_IO.rx_clk_cfg.rx_clk_i_inv = !PARL_IO.rx_clk_cfg.rx_clk_i_inv;
                printf("[EDGE] RX SAMPLE EDGE TOGGLED -> %s (rx_clk_i_inv=%d)\n",
                       PARL_IO.rx_clk_cfg.rx_clk_i_inv ? "NEG" : "POS",
                       (int)PARL_IO.rx_clk_cfg.rx_clk_i_inv);
            } else {
                uint32_t rx_dscr = 0, tx_dscr = 0;
                uint32_t rx_off = get_rx_dma_offset(&rx_dscr);
                uint32_t tx_off = get_tx_dma_offset(&tx_dscr);
                uint32_t dist = (rx_off >= tx_off) ? (rx_off - tx_off) : (sizeof(s_raw_ring) - tx_off + rx_off);
                int rx_nodes = patch_descriptors_clear_eof(s_rx_dma_ch, true);
                int tx_nodes = patch_descriptors_clear_eof(s_tx_dma_ch, false);
                printf("\n=======================================================\n");
                printf(" C5VRX-3 SEAMLESS 32K (Zero-EOF Descriptor Ring)\n");
                printf(" GDMA Ring:                  dist=%lu (rx_off=%lu, tx_off=%lu)\n",
                       (unsigned long)dist, (unsigned long)rx_off, (unsigned long)tx_off);
                printf(" Descriptors:                rx_dscr=0x%08lx, tx_dscr=0x%08lx\n",
                       (unsigned long)rx_dscr, (unsigned long)tx_dscr);
                printf(" Zero-EOF Status:            RX patched=%d nodes, TX patched=%d nodes\n",
                       rx_nodes, tx_nodes);
                printf(" PARLIO RX FIFO overflow:    %lu (raw=%d)\n",
                       (unsigned long)s_hw_counters.parl_rx_wovf_count,
                       PARL_IO.int_raw.rx_fifo_wovf_int_raw);
                printf(" PARLIO TX FIFO empty (udf): %lu (raw=%d)\n",
                       (unsigned long)s_hw_counters.parl_tx_rempty_count,
                       PARL_IO.int_raw.tx_fifo_rempty_int_raw);
                printf(" PARLIO TX EOF:              %lu (raw=%d)\n",
                       (unsigned long)s_hw_counters.parl_tx_eof_count,
                       PARL_IO.int_raw.tx_eof_int_raw);
                printf(" BitScrambler TX empty:      %d\n",
                       BITSCRAMBLER.state[1].fifo_empty);
                printf(" RX Sample Edge:             %s (rx_clk_i_inv=%d)\n",
                       PARL_IO.rx_clk_cfg.rx_clk_i_inv ? "NEG" : "POS",
                       (int)PARL_IO.rx_clk_cfg.rx_clk_i_inv);
                printf(" RF Gain forced:             %s (idx=%u, reg=0x%08lx)\n",
                       s_gain_forced ? "YES" : "NO", s_forced_gain, (unsigned long)rf_get_rx_gain_reg());
                printf(" Keys: '+' / '-' adjust gain, 'a' auto, 'f' toggle, 'e' toggle edge\n");
                printf("=======================================================\n\n");
            }
            fflush(stdout);
        }
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

/* ----- Main entry point ----- */

esp_err_t video_start(void)
{
    /* Zero the ring before starting. Flush to DMA-visible SRAM. */
    memset(s_raw_ring, 0, sizeof(s_raw_ring));
    (void)esp_cache_msync(s_raw_ring, sizeof(s_raw_ring),
                          ESP_CACHE_MSYNC_FLAG_DIR_C2M);

    esp_err_t err;

    if ((err = prepare_rx()) != ESP_OK) return err;
    if ((err = prepare_tx()) != ESP_OK) return err;

    /* Start RX cyclic ring. GDMA begins writing at s_raw_ring[0]. */
    if ((err = start_rx()) != ESP_OK) return err;

    /* Put PARLIO RX into pure continuous hardware mode:
     * 1. Disable all GDMA RX channel interrupts so the CPU is never interrupted
     *    (~9,775 ISRs/sec eliminated!).
     * 2. Set rx_eof_gen_sel = 1 (external enable, non-existent in soft mode)
     *    so PARLIO RX never generates an EOF stall event.
     * This matches PARLIO TX's unbroken hardware loop, eliminating pointer drift! */
    AHB_DMA.in_intr[0].ena.val = 0;
    AHB_DMA.in_intr[1].ena.val = 0;
    AHB_DMA.in_intr[2].ena.val = 0;
    PARL_IO.rx_genrl_cfg.rx_eof_gen_sel = 1;

    /* Establish producer/consumer separation before starting TX.
     * Use quarter of the ring size (8192 bytes = 204.8 µs).
     * Delay = (RAW_RING_BYTES / 4) bytes / 40,000,000 bytes/s */
    esp_rom_delay_us((RAW_RING_BYTES / 4u) * 1000000u / IQ_RATE_HZ);

    if ((err = start_tx()) != ESP_OK) return err;

    /* Discover AHB_DMA channels assigned to PARL_IO (peripheral ID 9) */
    for (int i = 0; i < 3; i++) {
        if (AHB_DMA.channel[i].in.in_peri_sel.peri_in_sel_chn == 9) {
            s_rx_dma_ch = i;
        }
        if (AHB_DMA.channel[i].out.out_peri_sel.peri_out_sel_chn == 9) {
            s_tx_dma_ch = i;
        }
    }

    /* Clear suc_eof on ALL GDMA descriptors for both RX and TX to eliminate
     * hardware wrap EOF bubbles completely! The buffer becomes a truly infinite ring. */
    int rx_nodes = patch_descriptors_clear_eof(s_rx_dma_ch, true);
    int tx_nodes = patch_descriptors_clear_eof(s_tx_dma_ch, false);

    /* Start interactive console for on-demand diagnostics (zero periodic CPU/bus traffic) */
    xTaskCreate(console_diag_task, "console_diag", 3072, NULL, 1, NULL);

    /* Print startup stamp (visible on serial monitor at boot). */
    ESP_EARLY_LOGW(TAG,
        "\n=======================================================\n"
        " C5VRX-3  Seamless 32K Phase5 receiver (Zero-EOF Circular GDMA)\n"
        " Clock:   PARLIO_CLK_SRC_DEFAULT 40MHz (SPLL internal)\n"
        " Telemetry: Live GDMA ring pointer tracking (rx_ch=%d, tx_ch=%d)\n"
        " Buffer:  32,768 bytes cyclic ring (Zero-EOF patched: RX=%d TX=%d)\n"
        " RX:      40 MS/s POS edge, 32,768 bytes pure HW cyclic GDMA\n"
        " Demod:   Phase5 50ns / P%u / G%u / current-minus-previous\n"
        " TX:      40 MHz [D,D] / eof=downstream / tail=0\n"
        " Lock:    GDMA ISRs disabled, RX EOF disabled, suc_eof=0 cleared\n"
        " CPU:     done (hardware runs in unbroken infinite loop)\n"
        "=======================================================\n",
        s_rx_dma_ch, s_tx_dma_ch, rx_nodes, tx_nodes, DAC_IDLE_CODE, 2u);

    return ESP_OK;
}
