#!/usr/bin/env python3
"""4-tap Catmull-Rom (cubic convolution, a = -0.5) polyphase coefficients, 32 phases, Q7.

Tap j (0..3) weights source sample n0 - 1 + j for a position n0 + t, t = phase / 32.
Each row sums to exactly 128: the rounding residue goes to the largest tap.
Writes rtl/out/cr_coef.vh (a Verilog function) when run; the same table is imported by
model/scaler_ref.py, so the RTL and the host model share one source.
"""
from pathlib import Path

PHASES = 32


def row(ph: int) -> list[int]:
    t = ph / PHASES
    w = [(-t**3 + 2 * t**2 - t) / 2,
         (3 * t**3 - 5 * t**2 + 2) / 2,
         (-3 * t**3 + 4 * t**2 + t) / 2,
         (t**3 - t**2) / 2]
    q = [round(x * 128) for x in w]
    big = max(range(4), key=lambda j: w[j])
    q[big] += 128 - sum(q)
    return q


TABLE = [row(p) for p in range(PHASES)]


def write_vh(path: Path) -> None:
    lines = ["// Generated by model/scaler_coef.py: 4-tap Catmull-Rom, 32 phases, Q7 (rows sum to 128).",
             "function [35:0] cr_coef(input [4:0] ph);   // {c3, c2, c1, c0}, 9-bit signed each",
             "    case (ph)"]
    for p, q in enumerate(TABLE):
        f = ", ".join(f"9'sd{v}" if v >= 0 else f"-9'sd{-v}" for v in reversed(q))
        lines.append(f"        5'd{p}: cr_coef = {{{f}}};")
    lines += ["        default: cr_coef = 36'd0;", "    endcase", "endfunction", ""]
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    write_vh(Path(__file__).resolve().parent.parent / "rtl/out/cr_coef.vh")
    for p in (0, 8, 16, 24):
        print(p, TABLE[p])
