#!/usr/bin/env python3
"""4-tap polyphase coefficients, 32 phases, Q7: Catmull-Rom (cubic convolution, a = -0.5) for
luma, cubic B-spline for chroma. The B-spline is all-positive and low-pass (1/6 [1 4 1] on the
grid, about -9.5 dB at the source Nyquist): the decoded colour has far more fine-scale noise than
colour detail (MEASUREMENTS M86), so the scaler smooths it vertically and horizontally.

Tap j (0..3) weights source sample n0 - 1 + j for a position n0 + t, t = phase / 32.
Each row sums to exactly 128: the rounding residue goes to the largest tap.
Writes rtl/out/cr_coef.vh (a Verilog function) when run; the same table is imported by
model/scaler_ref.py, so the RTL and the host model share one source.
"""
from pathlib import Path

PHASES = 32


def q7(w: list[float]) -> list[int]:
    q = [round(x * 128) for x in w]
    big = max(range(4), key=lambda j: w[j])
    q[big] += 128 - sum(q)
    return q


def row(ph: int) -> list[int]:
    t = ph / PHASES
    return q7([(-t**3 + 2 * t**2 - t) / 2, (3 * t**3 - 5 * t**2 + 2) / 2,
               (-3 * t**3 + 4 * t**2 + t) / 2, (t**3 - t**2) / 2])


def row_bs(ph: int) -> list[int]:
    t = ph / PHASES
    return q7([(1 - t)**3 / 6, (3 * t**3 - 6 * t**2 + 4) / 6, (-3 * t**3 + 3 * t**2 + 3 * t + 1) / 6, t**3 / 6])


TABLE = [row(p) for p in range(PHASES)]
TABLE_BS = [row_bs(p) for p in range(PHASES)]


def vh_function(name: str, table: list[list[int]], what: str) -> list[str]:
    lines = [f"// {what}, 32 phases, Q7 (rows sum to 128).",
             f"function [35:0] {name}(input [4:0] ph);   // {{c3, c2, c1, c0}}, 9-bit signed each",
             "    case (ph)"]
    for p, q in enumerate(table):
        f = ", ".join(f"9'sd{v}" if v >= 0 else f"-9'sd{-v}" for v in reversed(q))
        lines.append(f"        5'd{p}: {name} = {{{f}}};")
    return lines + [f"        default: {name} = 36'd0;", "    endcase", "endfunction", ""]


def write_vh(path: Path) -> None:
    lines = ["// Generated by model/scaler_coef.py."]
    lines += vh_function("cr_coef", TABLE, "4-tap Catmull-Rom (luma)")
    lines += vh_function("bs_coef", TABLE_BS, "4-tap cubic B-spline (chroma)")
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    write_vh(Path(__file__).resolve().parent.parent / "rtl/out/cr_coef.vh")
    for p in (0, 8, 16, 24):
        print(p, TABLE[p])
