#!/usr/bin/env python3
"""Derive the Gowin EDA pin constraints from ../tangnano20k.cst (the nextpnr file):
- a differential pair is constrained on its _p pin only, as "p,n" (Gowin rejects the _n pin),
- the in-package SDRAM pins are left out (Gowin connects O_sdram_* / IO_sdram_dq by name and
  rejects location constraints on them, error CT2017)."""
import re
from pathlib import Path

src = Path(__file__).resolve().parents[1] / "tangnano20k.cst"
lines = src.read_text().splitlines()
loc = {m.group(1): m.group(2) for m in (re.match(r'IO_LOC\s+"([^"]+)"\s+(\S+);', l) for l in lines) if m}
out = [f"// generated by gowin/make_cst.py from tangnano20k.cst - do not edit"]
for l in lines:
    m = re.match(r'(IO_LOC|IO_PORT)\s+"([^"]+)"', l)
    if m and "sdram" in m.group(2):
        continue
    if m and re.search(r"_n(\[\d+\])?$", m.group(2)) and m.group(2).replace("_n", "_p", 1) in loc:
        continue
    if m and m.group(1) == "IO_LOC" and re.search(r"_p(\[\d+\])?$", m.group(2)):
        n = m.group(2).replace("_p", "_n", 1)
        if n in loc:
            l = f'IO_LOC  "{m.group(2)}" {loc[m.group(2)]},{loc[n]};'
    out.append(l)
(Path(__file__).parent / "tangnano20k.cst").write_text("\n".join(out) + "\n")
