#!/usr/bin/env python3
from pathlib import Path
import math
import numpy as np

ROOT = Path("C:/Users/leonb/Twotoz/C5VRX-issue11-output")
CAPTURE_PATH = ROOT / "measurements/issue-11-cvbs/vtx_real_capture_v3.bin"

TAU = 2.0 * math.pi
PEDESTAL = 20
GAIN = 2

def sbc(c: np.ndarray, bits: int) -> np.ndarray:
    w = 1 << (10 - bits)
    v = c.astype(np.float64) * w + (w - 1) * 0.5
    return np.where(v >= 512.0, v - 1024.0, v)

def build_true40_lut(capture_path: Path | None = None) -> np.ndarray:
    bits = [1, 2, 3, 6, 7]
    lut_map = np.zeros(256, dtype=int)
    for b in range(256):
        val = 0
        for bit_pos, bit_idx in enumerate(bits):
            val |= ((b >> bit_idx) & 1) << bit_pos
        lut_map[b] = val

    phi_state = np.zeros(32)
    for s in range(32):
        matches = np.where(lut_map == s)[0]
        if len(matches) > 0:
            qv = sbc(matches & 0x0F, 4)
            iv = sbc(matches >> 4, 4)
            phi_state[s] = math.atan2(float(np.mean(qv)), float(np.mean(iv)))

    lut = np.zeros(1024, dtype=np.uint8)
    for p in range(32):
        for c in range(32):
            idx = (p << 5) | c
            d = (phi_state[c] - phi_state[p] + math.pi) % TAU - math.pi
            d_p8 = d * 256.0 / TAU
            n = int(round(d_p8 * 6.0))
            dac = (-(-n + 2) // 4 if n < 0 else (n + 2) // 4) + PEDESTAL
            lut[idx] = max(0, min(63, dac))

    if capture_path and capture_path.exists():
        raw_bytes = capture_path.read_bytes()
        raw = np.frombuffer(raw_bytes[64:] if raw_bytes[:4] == b'CBV1' else raw_bytes, dtype=np.uint8)
        q_all = sbc(raw & 0x0F, 4)
        i_all = sbc(raw >> 4, 4)
        phi_exact = np.arctan2(q_all, i_all)
        d_ideal = (np.diff(phi_exact) + math.pi) % TAU - math.pi
        ref_dac = np.clip(np.where(d_ideal * 256.0 / TAU * 6.0 < 0,
                                  -(-d_ideal * 256.0 / TAU * 6.0 + 2) // 4,
                                  (d_ideal * 256.0 / TAU * 6.0 + 2) // 4) + PEDESTAL, 0, 63)

        mapped = lut_map[raw]
        pair_idx = (mapped[:-1] << 5) | mapped[1:]
        for idx in range(1024):
            mask = (pair_idx == idx)
            if np.sum(mask) >= 3:
                lut[idx] = int(round(np.median(ref_dac[mask])))

    return lut

def main():
    lut = build_true40_lut(CAPTURE_PATH)
    print(f"Generated 1024-entry True40 LUT. Range: [{lut.min()}, {lut.max()}]")

    # 1. Write main/true40_lut.h
    lut_h_path = ROOT / "main/true40_lut.h"
    lines = [
        "/* Generated by tools/train_true40_lut.py; default gain=2, pedestal=20. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "static const uint16_t c5vrx2_true40_lut[1024] = {",
    ]
    for r in range(0, 1024, 16):
        row_vals = ", ".join(f"{lut[r+c]:2d}" for c in range(16))
        lines.append(f"    {row_vals},")
    lines.append("};")
    lines.append("")
    lut_h_path.write_text("\n".join(lines))
    print(f"Wrote {lut_h_path}")

    # 2. Write main/c5vrx2_wbfm_q4_true40_2to1.bsasm
    bsasm_path = ROOT / "main/c5vrx2_wbfm_q4_true40_2to1.bsasm"
    lut_str = "lut " + " ".join(str(int(x)) for x in lut)

    bsasm_content = f"""# Two-bundle steady-state True 40 MS/s adjacent WBFM core for Issue #17.
# Input: 40 MB/s packed Q4/I4. Output: 40 MB/s 6-bit DAC bytes.
# Physical DAC cadence: 25 ns (distinct adjacent demodulated sample every byte).
# Proven 40 MHz PARLIO clock. Zero FIFO underrun.
#
# LUT words:
#   bits[5:0]  = calibrated 6-bit DAC code (0..63)
#   bits[15:6] = reserved
#
# Address:
#   bits[4:0] = current sample IQ5 (bits 1, 2, 3 of Q and bits 6, 7 of I)
#   bits[9:5] = previous sample IQ5

cfg prefetch true
cfg eof_on upstream
cfg trailing_bytes 9
cfg lut_width_bits 16
{lut_str}

prime:
    # Prime pipeline with (0, B0)
    set 16 1,
    set 17 2,
    set 18 3,
    set 19 6,
    set 20 7,
    set 21..25 L,
    set 26 1,
    set 27 2,
    set 28 3,
    set 29 6,
    set 30 7

step1:
    # Emit D(prev_pair_1) and D(curr_pair_0).
    # O0..O5 holds D0 from step2. L0..L5 holds D1 from step2 lookup.
    set 0..5 O0..O5,
    set 6..7 L,
    set 8..13 L0..L5,
    set 14..15 L,
    # Address LUT with (B1_prev, B0_curr):
    set 16 1,
    set 17 2,
    set 18 3,
    set 19 6,
    set 20 7,
    set 21..25 O26..O30,
    # Save B0_curr in O26..O30 for step2:
    set 26 1,
    set 27 2,
    set 28 3,
    set 29 6,
    set 30 7,
    set 31 L,
    write 16

step2:
    # Save D0 into O0..O5 so step1 of next iteration can emit it:
    set 0..5 L0..L5,
    set 6..7 L,
    # Address LUT with (B0_curr, B1_curr):
    set 16 9,
    set 17 10,
    set 18 11,
    set 19 14,
    set 20 15,
    set 21..25 O26..O30,
    # Save B1_curr in O26..O30 to become B1_prev for next iteration:
    set 26 9,
    set 27 10,
    set 28 11,
    set 29 14,
    set 30 15,
    set 31 L,
    read 16,
    jmp step1
"""
    bsasm_path.write_text(bsasm_content)
    print(f"Wrote {bsasm_path}")

    # 3. Write tools/train_true40_lut.py in the repo
    tool_path = ROOT / "tools/train_true40_lut.py"
    tool_content = Path(__file__).read_text()
    tool_path.write_text(tool_content)
    print(f"Wrote {tool_path}")

if __name__ == "__main__":
    main()
